// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: attack_plan.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createAttackPlan = `-- name: CreateAttackPlan :one
INSERT INTO attack_plans (flow_id, objective_key, objective, status, planner)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, flow_id, objective_key, objective, status, version, planner, created_at, updated_at
`

type CreateAttackPlanParams struct {
	FlowID       int64            `json:"flow_id"`
	ObjectiveKey string           `json:"objective_key"`
	Objective    string           `json:"objective"`
	Status       AttackPlanStatus `json:"status"`
	Planner      string           `json:"planner"`
}

func (q *Queries) CreateAttackPlan(ctx context.Context, arg CreateAttackPlanParams) (AttackPlan, error) {
	row := q.db.QueryRowContext(ctx, createAttackPlan,
		arg.FlowID,
		arg.ObjectiveKey,
		arg.Objective,
		arg.Status,
		arg.Planner,
	)
	var i AttackPlan
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.ObjectiveKey,
		&i.Objective,
		&i.Status,
		&i.Version,
		&i.Planner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAttackPlanActionSubtaskBinding = `-- name: CreateAttackPlanActionSubtaskBinding :one
INSERT INTO attack_plan_bindings (plan_id, flow_id, node_id, task_id, subtask_id)
SELECT $1, $2, n.id, $4, $5
FROM attack_plan_nodes n
WHERE n.id = $3 AND n.plan_id = $1 AND n.flow_id = $2 AND n.kind = 'action'
RETURNING id, plan_id, flow_id, node_id, task_id, subtask_id, created_at
`

type CreateAttackPlanActionSubtaskBindingParams struct {
	PlanID    int64         `json:"plan_id"`
	FlowID    int64         `json:"flow_id"`
	ID        int64         `json:"id"`
	TaskID    sql.NullInt64 `json:"task_id"`
	SubtaskID sql.NullInt64 `json:"subtask_id"`
}

func (q *Queries) CreateAttackPlanActionSubtaskBinding(ctx context.Context, arg CreateAttackPlanActionSubtaskBindingParams) (AttackPlanBinding, error) {
	row := q.db.QueryRowContext(ctx, createAttackPlanActionSubtaskBinding,
		arg.PlanID,
		arg.FlowID,
		arg.ID,
		arg.TaskID,
		arg.SubtaskID,
	)
	var i AttackPlanBinding
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.FlowID,
		&i.NodeID,
		&i.TaskID,
		&i.SubtaskID,
		&i.CreatedAt,
	)
	return i, err
}

const createAttackPlanBinding = `-- name: CreateAttackPlanBinding :one
INSERT INTO attack_plan_bindings (plan_id, flow_id, node_id, task_id, subtask_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, plan_id, flow_id, node_id, task_id, subtask_id, created_at
`

type CreateAttackPlanBindingParams struct {
	PlanID    int64         `json:"plan_id"`
	FlowID    int64         `json:"flow_id"`
	NodeID    sql.NullInt64 `json:"node_id"`
	TaskID    sql.NullInt64 `json:"task_id"`
	SubtaskID sql.NullInt64 `json:"subtask_id"`
}

func (q *Queries) CreateAttackPlanBinding(ctx context.Context, arg CreateAttackPlanBindingParams) (AttackPlanBinding, error) {
	row := q.db.QueryRowContext(ctx, createAttackPlanBinding,
		arg.PlanID,
		arg.FlowID,
		arg.NodeID,
		arg.TaskID,
		arg.SubtaskID,
	)
	var i AttackPlanBinding
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.FlowID,
		&i.NodeID,
		&i.TaskID,
		&i.SubtaskID,
		&i.CreatedAt,
	)
	return i, err
}

const createAttackPlanEdge = `-- name: CreateAttackPlanEdge :one
INSERT INTO attack_plan_edges (plan_id, flow_id, from_node_id, to_node_id, kind)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, plan_id, flow_id, from_node_id, to_node_id, kind, created_at
`

type CreateAttackPlanEdgeParams struct {
	PlanID     int64              `json:"plan_id"`
	FlowID     int64              `json:"flow_id"`
	FromNodeID int64              `json:"from_node_id"`
	ToNodeID   int64              `json:"to_node_id"`
	Kind       AttackPlanEdgeKind `json:"kind"`
}

func (q *Queries) CreateAttackPlanEdge(ctx context.Context, arg CreateAttackPlanEdgeParams) (AttackPlanEdge, error) {
	row := q.db.QueryRowContext(ctx, createAttackPlanEdge,
		arg.PlanID,
		arg.FlowID,
		arg.FromNodeID,
		arg.ToNodeID,
		arg.Kind,
	)
	var i AttackPlanEdge
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.FlowID,
		&i.FromNodeID,
		&i.ToNodeID,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const createAttackPlanEvidence = `-- name: CreateAttackPlanEvidence :one
INSERT INTO attack_plan_evidence (
  plan_id, flow_id, node_id, run_id, revision_from, revision_to, provenance
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, plan_id, flow_id, node_id, run_id, revision_from, revision_to, provenance, created_at
`

type CreateAttackPlanEvidenceParams struct {
	PlanID       int64           `json:"plan_id"`
	FlowID       int64           `json:"flow_id"`
	NodeID       sql.NullInt64   `json:"node_id"`
	RunID        sql.NullInt64   `json:"run_id"`
	RevisionFrom int64           `json:"revision_from"`
	RevisionTo   int64           `json:"revision_to"`
	Provenance   json.RawMessage `json:"provenance"`
}

func (q *Queries) CreateAttackPlanEvidence(ctx context.Context, arg CreateAttackPlanEvidenceParams) (AttackPlanEvidence, error) {
	row := q.db.QueryRowContext(ctx, createAttackPlanEvidence,
		arg.PlanID,
		arg.FlowID,
		arg.NodeID,
		arg.RunID,
		arg.RevisionFrom,
		arg.RevisionTo,
		arg.Provenance,
	)
	var i AttackPlanEvidence
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.FlowID,
		&i.NodeID,
		&i.RunID,
		&i.RevisionFrom,
		&i.RevisionTo,
		&i.Provenance,
		&i.CreatedAt,
	)
	return i, err
}

const createAttackPlanNode = `-- name: CreateAttackPlanNode :one
INSERT INTO attack_plan_nodes (plan_id, flow_id, node_key, kind, status, title, description, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, plan_id, flow_id, node_key, kind, status, title, description, payload, version, created_at, updated_at
`

type CreateAttackPlanNodeParams struct {
	PlanID      int64                `json:"plan_id"`
	FlowID      int64                `json:"flow_id"`
	NodeKey     string               `json:"node_key"`
	Kind        AttackPlanNodeKind   `json:"kind"`
	Status      AttackPlanNodeStatus `json:"status"`
	Title       string               `json:"title"`
	Description string               `json:"description"`
	Payload     json.RawMessage      `json:"payload"`
}

func (q *Queries) CreateAttackPlanNode(ctx context.Context, arg CreateAttackPlanNodeParams) (AttackPlanNode, error) {
	row := q.db.QueryRowContext(ctx, createAttackPlanNode,
		arg.PlanID,
		arg.FlowID,
		arg.NodeKey,
		arg.Kind,
		arg.Status,
		arg.Title,
		arg.Description,
		arg.Payload,
	)
	var i AttackPlanNode
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.FlowID,
		&i.NodeKey,
		&i.Kind,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.Payload,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAttackPlanRun = `-- name: CreateAttackPlanRun :one
INSERT INTO attack_plan_runs (
  plan_id, flow_id, requested_version, world_state_revision, idempotency_key, planner
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (plan_id, idempotency_key) DO UPDATE
SET idempotency_key = EXCLUDED.idempotency_key
RETURNING id, plan_id, flow_id, status, requested_version, resulting_version, world_state_revision, idempotency_key, planner, error, started_at, finished_at
`

type CreateAttackPlanRunParams struct {
	PlanID             int64  `json:"plan_id"`
	FlowID             int64  `json:"flow_id"`
	RequestedVersion   int64  `json:"requested_version"`
	WorldStateRevision int64  `json:"world_state_revision"`
	IdempotencyKey     string `json:"idempotency_key"`
	Planner            string `json:"planner"`
}

func (q *Queries) CreateAttackPlanRun(ctx context.Context, arg CreateAttackPlanRunParams) (AttackPlanRun, error) {
	row := q.db.QueryRowContext(ctx, createAttackPlanRun,
		arg.PlanID,
		arg.FlowID,
		arg.RequestedVersion,
		arg.WorldStateRevision,
		arg.IdempotencyKey,
		arg.Planner,
	)
	var i AttackPlanRun
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.FlowID,
		&i.Status,
		&i.RequestedVersion,
		&i.ResultingVersion,
		&i.WorldStateRevision,
		&i.IdempotencyKey,
		&i.Planner,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const deleteAttackPlanEdge = `-- name: DeleteAttackPlanEdge :exec
DELETE FROM attack_plan_edges
WHERE id = $1 AND plan_id = $2 AND flow_id = $3
`

type DeleteAttackPlanEdgeParams struct {
	ID     int64 `json:"id"`
	PlanID int64 `json:"plan_id"`
	FlowID int64 `json:"flow_id"`
}

func (q *Queries) DeleteAttackPlanEdge(ctx context.Context, arg DeleteAttackPlanEdgeParams) error {
	_, err := q.db.ExecContext(ctx, deleteAttackPlanEdge, arg.ID, arg.PlanID, arg.FlowID)
	return err
}

const deleteAttackPlanEdges = `-- name: DeleteAttackPlanEdges :exec
DELETE FROM attack_plan_edges
WHERE plan_id = $1 AND flow_id = $2
`

type DeleteAttackPlanEdgesParams struct {
	PlanID int64 `json:"plan_id"`
	FlowID int64 `json:"flow_id"`
}

func (q *Queries) DeleteAttackPlanEdges(ctx context.Context, arg DeleteAttackPlanEdgesParams) error {
	_, err := q.db.ExecContext(ctx, deleteAttackPlanEdges, arg.PlanID, arg.FlowID)
	return err
}

const deleteAttackPlanNode = `-- name: DeleteAttackPlanNode :exec
DELETE FROM attack_plan_nodes
WHERE id = $1 AND plan_id = $2 AND flow_id = $3
`

type DeleteAttackPlanNodeParams struct {
	ID     int64 `json:"id"`
	PlanID int64 `json:"plan_id"`
	FlowID int64 `json:"flow_id"`
}

func (q *Queries) DeleteAttackPlanNode(ctx context.Context, arg DeleteAttackPlanNodeParams) error {
	_, err := q.db.ExecContext(ctx, deleteAttackPlanNode, arg.ID, arg.PlanID, arg.FlowID)
	return err
}

const deleteAttackPlanNodes = `-- name: DeleteAttackPlanNodes :exec
DELETE FROM attack_plan_nodes
WHERE plan_id = $1 AND flow_id = $2
`

type DeleteAttackPlanNodesParams struct {
	PlanID int64 `json:"plan_id"`
	FlowID int64 `json:"flow_id"`
}

func (q *Queries) DeleteAttackPlanNodes(ctx context.Context, arg DeleteAttackPlanNodesParams) error {
	_, err := q.db.ExecContext(ctx, deleteAttackPlanNodes, arg.PlanID, arg.FlowID)
	return err
}

const getActiveAttackPlanByObjective = `-- name: GetActiveAttackPlanByObjective :one
SELECT id, flow_id, objective_key, objective, status, version, planner, created_at, updated_at FROM attack_plans
WHERE flow_id = $1 AND objective_key = $2 AND status = 'active'
`

type GetActiveAttackPlanByObjectiveParams struct {
	FlowID       int64  `json:"flow_id"`
	ObjectiveKey string `json:"objective_key"`
}

func (q *Queries) GetActiveAttackPlanByObjective(ctx context.Context, arg GetActiveAttackPlanByObjectiveParams) (AttackPlan, error) {
	row := q.db.QueryRowContext(ctx, getActiveAttackPlanByObjective, arg.FlowID, arg.ObjectiveKey)
	var i AttackPlan
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.ObjectiveKey,
		&i.Objective,
		&i.Status,
		&i.Version,
		&i.Planner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttackPlan = `-- name: GetAttackPlan :one
SELECT id, flow_id, objective_key, objective, status, version, planner, created_at, updated_at FROM attack_plans
WHERE id = $1 AND flow_id = $2
`

type GetAttackPlanParams struct {
	ID     int64 `json:"id"`
	FlowID int64 `json:"flow_id"`
}

func (q *Queries) GetAttackPlan(ctx context.Context, arg GetAttackPlanParams) (AttackPlan, error) {
	row := q.db.QueryRowContext(ctx, getAttackPlan, arg.ID, arg.FlowID)
	var i AttackPlan
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.ObjectiveKey,
		&i.Objective,
		&i.Status,
		&i.Version,
		&i.Planner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttackPlanNode = `-- name: GetAttackPlanNode :one
SELECT id, plan_id, flow_id, node_key, kind, status, title, description, payload, version, created_at, updated_at FROM attack_plan_nodes
WHERE id = $1 AND plan_id = $2 AND flow_id = $3
`

type GetAttackPlanNodeParams struct {
	ID     int64 `json:"id"`
	PlanID int64 `json:"plan_id"`
	FlowID int64 `json:"flow_id"`
}

func (q *Queries) GetAttackPlanNode(ctx context.Context, arg GetAttackPlanNodeParams) (AttackPlanNode, error) {
	row := q.db.QueryRowContext(ctx, getAttackPlanNode, arg.ID, arg.PlanID, arg.FlowID)
	var i AttackPlanNode
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.FlowID,
		&i.NodeKey,
		&i.Kind,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.Payload,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttackPlanNodeByKey = `-- name: GetAttackPlanNodeByKey :one
SELECT id, plan_id, flow_id, node_key, kind, status, title, description, payload, version, created_at, updated_at FROM attack_plan_nodes
WHERE plan_id = $1 AND flow_id = $2 AND node_key = $3
`

type GetAttackPlanNodeByKeyParams struct {
	PlanID  int64  `json:"plan_id"`
	FlowID  int64  `json:"flow_id"`
	NodeKey string `json:"node_key"`
}

func (q *Queries) GetAttackPlanNodeByKey(ctx context.Context, arg GetAttackPlanNodeByKeyParams) (AttackPlanNode, error) {
	row := q.db.QueryRowContext(ctx, getAttackPlanNodeByKey, arg.PlanID, arg.FlowID, arg.NodeKey)
	var i AttackPlanNode
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.FlowID,
		&i.NodeKey,
		&i.Kind,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.Payload,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttackPlanRunByIdempotencyKey = `-- name: GetAttackPlanRunByIdempotencyKey :one
SELECT id, plan_id, flow_id, status, requested_version, resulting_version, world_state_revision, idempotency_key, planner, error, started_at, finished_at FROM attack_plan_runs
WHERE plan_id = $1 AND flow_id = $2 AND idempotency_key = $3
`

type GetAttackPlanRunByIdempotencyKeyParams struct {
	PlanID         int64  `json:"plan_id"`
	FlowID         int64  `json:"flow_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetAttackPlanRunByIdempotencyKey(ctx context.Context, arg GetAttackPlanRunByIdempotencyKeyParams) (AttackPlanRun, error) {
	row := q.db.QueryRowContext(ctx, getAttackPlanRunByIdempotencyKey, arg.PlanID, arg.FlowID, arg.IdempotencyKey)
	var i AttackPlanRun
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.FlowID,
		&i.Status,
		&i.RequestedVersion,
		&i.ResultingVersion,
		&i.WorldStateRevision,
		&i.IdempotencyKey,
		&i.Planner,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listAttackPlanBindings = `-- name: ListAttackPlanBindings :many
SELECT id, plan_id, flow_id, node_id, task_id, subtask_id, created_at FROM attack_plan_bindings
WHERE plan_id = $1 AND flow_id = $2
ORDER BY id ASC
`

type ListAttackPlanBindingsParams struct {
	PlanID int64 `json:"plan_id"`
	FlowID int64 `json:"flow_id"`
}

func (q *Queries) ListAttackPlanBindings(ctx context.Context, arg ListAttackPlanBindingsParams) ([]AttackPlanBinding, error) {
	rows, err := q.db.QueryContext(ctx, listAttackPlanBindings, arg.PlanID, arg.FlowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttackPlanBinding
	for rows.Next() {
		var i AttackPlanBinding
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.FlowID,
			&i.NodeID,
			&i.TaskID,
			&i.SubtaskID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttackPlanEdges = `-- name: ListAttackPlanEdges :many
SELECT id, plan_id, flow_id, from_node_id, to_node_id, kind, created_at FROM attack_plan_edges
WHERE plan_id = $1 AND flow_id = $2
ORDER BY id ASC
`

type ListAttackPlanEdgesParams struct {
	PlanID int64 `json:"plan_id"`
	FlowID int64 `json:"flow_id"`
}

func (q *Queries) ListAttackPlanEdges(ctx context.Context, arg ListAttackPlanEdgesParams) ([]AttackPlanEdge, error) {
	rows, err := q.db.QueryContext(ctx, listAttackPlanEdges, arg.PlanID, arg.FlowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttackPlanEdge
	for rows.Next() {
		var i AttackPlanEdge
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.FlowID,
			&i.FromNodeID,
			&i.ToNodeID,
			&i.Kind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttackPlanEvidence = `-- name: ListAttackPlanEvidence :many
SELECT id, plan_id, flow_id, node_id, run_id, revision_from, revision_to, provenance, created_at FROM attack_plan_evidence
WHERE plan_id = $1 AND flow_id = $2
ORDER BY revision_from ASC, revision_to ASC, id ASC
`

type ListAttackPlanEvidenceParams struct {
	PlanID int64 `json:"plan_id"`
	FlowID int64 `json:"flow_id"`
}

func (q *Queries) ListAttackPlanEvidence(ctx context.Context, arg ListAttackPlanEvidenceParams) ([]AttackPlanEvidence, error) {
	rows, err := q.db.QueryContext(ctx, listAttackPlanEvidence, arg.PlanID, arg.FlowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttackPlanEvidence
	for rows.Next() {
		var i AttackPlanEvidence
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.FlowID,
			&i.NodeID,
			&i.RunID,
			&i.RevisionFrom,
			&i.RevisionTo,
			&i.Provenance,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttackPlanEvidenceForRun = `-- name: ListAttackPlanEvidenceForRun :many
SELECT id, plan_id, flow_id, node_id, run_id, revision_from, revision_to, provenance, created_at FROM attack_plan_evidence
WHERE plan_id = $1 AND flow_id = $2 AND run_id = $3 AND node_id IS NULL
ORDER BY revision_from ASC, revision_to ASC, id ASC
`

type ListAttackPlanEvidenceForRunParams struct {
	PlanID int64         `json:"plan_id"`
	FlowID int64         `json:"flow_id"`
	RunID  sql.NullInt64 `json:"run_id"`
}

func (q *Queries) ListAttackPlanEvidenceForRun(ctx context.Context, arg ListAttackPlanEvidenceForRunParams) ([]AttackPlanEvidence, error) {
	rows, err := q.db.QueryContext(ctx, listAttackPlanEvidenceForRun, arg.PlanID, arg.FlowID, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttackPlanEvidence
	for rows.Next() {
		var i AttackPlanEvidence
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.FlowID,
			&i.NodeID,
			&i.RunID,
			&i.RevisionFrom,
			&i.RevisionTo,
			&i.Provenance,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttackPlanNodes = `-- name: ListAttackPlanNodes :many
SELECT id, plan_id, flow_id, node_key, kind, status, title, description, payload, version, created_at, updated_at FROM attack_plan_nodes
WHERE plan_id = $1 AND flow_id = $2
ORDER BY id ASC
`

type ListAttackPlanNodesParams struct {
	PlanID int64 `json:"plan_id"`
	FlowID int64 `json:"flow_id"`
}

func (q *Queries) ListAttackPlanNodes(ctx context.Context, arg ListAttackPlanNodesParams) ([]AttackPlanNode, error) {
	rows, err := q.db.QueryContext(ctx, listAttackPlanNodes, arg.PlanID, arg.FlowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttackPlanNode
	for rows.Next() {
		var i AttackPlanNode
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.FlowID,
			&i.NodeKey,
			&i.Kind,
			&i.Status,
			&i.Title,
			&i.Description,
			&i.Payload,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttackPlans = `-- name: ListAttackPlans :many
SELECT id, flow_id, objective_key, objective, status, version, planner, created_at, updated_at FROM attack_plans
WHERE flow_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListAttackPlans(ctx context.Context, flowID int64) ([]AttackPlan, error) {
	rows, err := q.db.QueryContext(ctx, listAttackPlans, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttackPlan
	for rows.Next() {
		var i AttackPlan
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.ObjectiveKey,
			&i.Objective,
			&i.Status,
			&i.Version,
			&i.Planner,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAttackPlan = `-- name: LockAttackPlan :one
SELECT id, flow_id, objective_key, objective, status, version, planner, created_at, updated_at FROM attack_plans
WHERE id = $1 AND flow_id = $2
FOR UPDATE
`

type LockAttackPlanParams struct {
	ID     int64 `json:"id"`
	FlowID int64 `json:"flow_id"`
}

func (q *Queries) LockAttackPlan(ctx context.Context, arg LockAttackPlanParams) (AttackPlan, error) {
	row := q.db.QueryRowContext(ctx, lockAttackPlan, arg.ID, arg.FlowID)
	var i AttackPlan
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.ObjectiveKey,
		&i.Objective,
		&i.Status,
		&i.Version,
		&i.Planner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockAttackPlanFlow = `-- name: LockAttackPlanFlow :one
SELECT id FROM flows
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockAttackPlanFlow(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, lockAttackPlanFlow, id)
	err := row.Scan(&id)
	return id, err
}

const lockAttackPlanRunByIdempotencyKey = `-- name: LockAttackPlanRunByIdempotencyKey :one
SELECT id, plan_id, flow_id, status, requested_version, resulting_version, world_state_revision, idempotency_key, planner, error, started_at, finished_at FROM attack_plan_runs
WHERE plan_id = $1 AND flow_id = $2 AND idempotency_key = $3
FOR UPDATE
`

type LockAttackPlanRunByIdempotencyKeyParams struct {
	PlanID         int64  `json:"plan_id"`
	FlowID         int64  `json:"flow_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) LockAttackPlanRunByIdempotencyKey(ctx context.Context, arg LockAttackPlanRunByIdempotencyKeyParams) (AttackPlanRun, error) {
	row := q.db.QueryRowContext(ctx, lockAttackPlanRunByIdempotencyKey, arg.PlanID, arg.FlowID, arg.IdempotencyKey)
	var i AttackPlanRun
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.FlowID,
		&i.Status,
		&i.RequestedVersion,
		&i.ResultingVersion,
		&i.WorldStateRevision,
		&i.IdempotencyKey,
		&i.Planner,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const transitionAttackPlanRun = `-- name: TransitionAttackPlanRun :one
UPDATE attack_plan_runs
SET status = $4, resulting_version = $5,
    finished_at = CASE WHEN $4 = 'running'::attack_plan_run_status THEN NULL ELSE CURRENT_TIMESTAMP END,
    error = $6
WHERE id = $1 AND plan_id = $2 AND flow_id = $3
RETURNING id, plan_id, flow_id, status, requested_version, resulting_version, world_state_revision, idempotency_key, planner, error, started_at, finished_at
`

type TransitionAttackPlanRunParams struct {
	ID               int64               `json:"id"`
	PlanID           int64               `json:"plan_id"`
	FlowID           int64               `json:"flow_id"`
	Status           AttackPlanRunStatus `json:"status"`
	ResultingVersion sql.NullInt64       `json:"resulting_version"`
	Error            json.RawMessage     `json:"error"`
}

func (q *Queries) TransitionAttackPlanRun(ctx context.Context, arg TransitionAttackPlanRunParams) (AttackPlanRun, error) {
	row := q.db.QueryRowContext(ctx, transitionAttackPlanRun,
		arg.ID,
		arg.PlanID,
		arg.FlowID,
		arg.Status,
		arg.ResultingVersion,
		arg.Error,
	)
	var i AttackPlanRun
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.FlowID,
		&i.Status,
		&i.RequestedVersion,
		&i.ResultingVersion,
		&i.WorldStateRevision,
		&i.IdempotencyKey,
		&i.Planner,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const updateAttackPlanNodeVersion = `-- name: UpdateAttackPlanNodeVersion :one
UPDATE attack_plan_nodes
SET status = $4, title = $5, description = $6, payload = $7,
    version = version + 1, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND plan_id = $2 AND flow_id = $3 AND version = $8
RETURNING id, plan_id, flow_id, node_key, kind, status, title, description, payload, version, created_at, updated_at
`

type UpdateAttackPlanNodeVersionParams struct {
	ID          int64                `json:"id"`
	PlanID      int64                `json:"plan_id"`
	FlowID      int64                `json:"flow_id"`
	Status      AttackPlanNodeStatus `json:"status"`
	Title       string               `json:"title"`
	Description string               `json:"description"`
	Payload     json.RawMessage      `json:"payload"`
	Version     int64                `json:"version"`
}

func (q *Queries) UpdateAttackPlanNodeVersion(ctx context.Context, arg UpdateAttackPlanNodeVersionParams) (AttackPlanNode, error) {
	row := q.db.QueryRowContext(ctx, updateAttackPlanNodeVersion,
		arg.ID,
		arg.PlanID,
		arg.FlowID,
		arg.Status,
		arg.Title,
		arg.Description,
		arg.Payload,
		arg.Version,
	)
	var i AttackPlanNode
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.FlowID,
		&i.NodeKey,
		&i.Kind,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.Payload,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAttackPlanVersion = `-- name: UpdateAttackPlanVersion :one
UPDATE attack_plans
SET objective = $3, status = $4, planner = $5, version = version + 1, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND flow_id = $2 AND version = $6
RETURNING id, flow_id, objective_key, objective, status, version, planner, created_at, updated_at
`

type UpdateAttackPlanVersionParams struct {
	ID        int64            `json:"id"`
	FlowID    int64            `json:"flow_id"`
	Objective string           `json:"objective"`
	Status    AttackPlanStatus `json:"status"`
	Planner   string           `json:"planner"`
	Version   int64            `json:"version"`
}

func (q *Queries) UpdateAttackPlanVersion(ctx context.Context, arg UpdateAttackPlanVersionParams) (AttackPlan, error) {
	row := q.db.QueryRowContext(ctx, updateAttackPlanVersion,
		arg.ID,
		arg.FlowID,
		arg.Objective,
		arg.Status,
		arg.Planner,
		arg.Version,
	)
	var i AttackPlan
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.ObjectiveKey,
		&i.Objective,
		&i.Status,
		&i.Version,
		&i.Planner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
