// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: world_state_delivery.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/lib/pq"
)

const acceptClaimedPrimaryWorldStateResume = `-- name: AcceptClaimedPrimaryWorldStateResume :one
UPDATE agent_chain_waits
SET resume_pending = FALSE,
    resume_intent = '{}'::jsonb,
    lease_owner = NULL,
    lease_expires_at = NULL
WHERE msgchain_id = $1
  AND state = 'resolved'
  AND resolution_winner = 'world_state'
  AND pending_tool_call_id = $2
  AND resolution_ref = $3
  AND resume_pending = TRUE
  AND resume_intent = $4
  AND lease_owner = $5
  AND lease_expires_at > CURRENT_TIMESTAMP
RETURNING msgchain_id, flow_id, wait_kind, pending_tool_call_id, state, resolution_winner, resolution_ref, resolved_at, lease_owner, lease_expires_at, retry_count, next_attempt_at, resume_pending, resume_intent, created_at, updated_at
`

type AcceptClaimedPrimaryWorldStateResumeParams struct {
	MsgchainID        int64           `json:"msgchain_id"`
	PendingToolCallID sql.NullString  `json:"pending_tool_call_id"`
	ResolutionRef     sql.NullInt64   `json:"resolution_ref"`
	ResumeIntent      json.RawMessage `json:"resume_intent"`
	LeaseOwner        sql.NullString  `json:"lease_owner"`
}

func (q *Queries) AcceptClaimedPrimaryWorldStateResume(ctx context.Context, arg AcceptClaimedPrimaryWorldStateResumeParams) (AgentChainWait, error) {
	row := q.db.QueryRowContext(ctx, acceptClaimedPrimaryWorldStateResume,
		arg.MsgchainID,
		arg.PendingToolCallID,
		arg.ResolutionRef,
		arg.ResumeIntent,
		arg.LeaseOwner,
	)
	var i AgentChainWait
	err := row.Scan(
		&i.MsgchainID,
		&i.FlowID,
		&i.WaitKind,
		&i.PendingToolCallID,
		&i.State,
		&i.ResolutionWinner,
		&i.ResolutionRef,
		&i.ResolvedAt,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.RetryCount,
		&i.NextAttemptAt,
		&i.ResumePending,
		&i.ResumeIntent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const acknowledgeAgentTaskUpdatesExact = `-- name: AcknowledgeAgentTaskUpdatesExact :many
WITH requested AS (
  SELECT DISTINCT unnest($1::bigint[]) AS id
), eligible AS (
  SELECT atu.id
  FROM agent_task_updates atu
  INNER JOIN requested r ON r.id = atu.id
  INNER JOIN msgchains mc ON mc.id = $2 AND mc.flow_id = atu.flow_id
  WHERE atu.flow_id = $3
    AND atu.state = 'pending'
    AND (atu.recipient_msgchain_id IS NULL OR atu.recipient_msgchain_id = mc.id)
    AND mc.updated_at = $4
  FOR UPDATE OF atu
), valid AS (
  SELECT COUNT(*) = cardinality($1::bigint[])
    AND COUNT(*) = (SELECT COUNT(*) FROM eligible) AS ok
  FROM requested
), acknowledged AS (
  UPDATE agent_task_updates atu
  SET state = 'delivered',
      recipient_msgchain_id = $2,
      delivered_at = $4
  FROM eligible e
  WHERE atu.id = e.id AND (SELECT ok FROM valid)
  RETURNING atu.id, atu.flow_id, atu.sender_msgchain_id, atu.target_type, atu.target_task_id, atu.target_subtask_id, atu.target_assistant_id, atu.target_role, atu.target_msgchain_id, atu.instruction, atu.selected_facts, atu.source_revisions, atu.state, atu.recipient_msgchain_id, atu.delivered_at, atu.rejected_at, atu.rejection_reason, atu.created_at, atu.updated_at
)
SELECT id, flow_id, sender_msgchain_id, target_type, target_task_id, target_subtask_id, target_assistant_id, target_role, target_msgchain_id, instruction, selected_facts, source_revisions, state, recipient_msgchain_id, delivered_at, rejected_at, rejection_reason, created_at, updated_at FROM acknowledged ORDER BY id ASC
`

type AcknowledgeAgentTaskUpdatesExactParams struct {
	UpdateIds           []int64      `json:"update_ids"`
	RecipientMsgchainID int64        `json:"recipient_msgchain_id"`
	FlowID              int64        `json:"flow_id"`
	DeliveredAt         sql.NullTime `json:"delivered_at"`
}

type AcknowledgeAgentTaskUpdatesExactRow struct {
	ID                  int64                `json:"id"`
	FlowID              int64                `json:"flow_id"`
	SenderMsgchainID    sql.NullInt64        `json:"sender_msgchain_id"`
	TargetType          AgentTaskTargetType  `json:"target_type"`
	TargetTaskID        sql.NullInt64        `json:"target_task_id"`
	TargetSubtaskID     sql.NullInt64        `json:"target_subtask_id"`
	TargetAssistantID   sql.NullInt64        `json:"target_assistant_id"`
	TargetRole          sql.NullString       `json:"target_role"`
	TargetMsgchainID    sql.NullInt64        `json:"target_msgchain_id"`
	Instruction         string               `json:"instruction"`
	SelectedFacts       json.RawMessage      `json:"selected_facts"`
	SourceRevisions     []int64              `json:"source_revisions"`
	State               AgentTaskUpdateState `json:"state"`
	RecipientMsgchainID sql.NullInt64        `json:"recipient_msgchain_id"`
	DeliveredAt         sql.NullTime         `json:"delivered_at"`
	RejectedAt          sql.NullTime         `json:"rejected_at"`
	RejectionReason     sql.NullString       `json:"rejection_reason"`
	CreatedAt           time.Time            `json:"created_at"`
	UpdatedAt           time.Time            `json:"updated_at"`
}

func (q *Queries) AcknowledgeAgentTaskUpdatesExact(ctx context.Context, arg AcknowledgeAgentTaskUpdatesExactParams) ([]AcknowledgeAgentTaskUpdatesExactRow, error) {
	rows, err := q.db.QueryContext(ctx, acknowledgeAgentTaskUpdatesExact,
		pq.Array(arg.UpdateIds),
		arg.RecipientMsgchainID,
		arg.FlowID,
		arg.DeliveredAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AcknowledgeAgentTaskUpdatesExactRow
	for rows.Next() {
		var i AcknowledgeAgentTaskUpdatesExactRow
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.SenderMsgchainID,
			&i.TargetType,
			&i.TargetTaskID,
			&i.TargetSubtaskID,
			&i.TargetAssistantID,
			&i.TargetRole,
			&i.TargetMsgchainID,
			&i.Instruction,
			&i.SelectedFacts,
			pq.Array(&i.SourceRevisions),
			&i.State,
			&i.RecipientMsgchainID,
			&i.DeliveredAt,
			&i.RejectedAt,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const advanceWorldStateChainCursor = `-- name: AdvanceWorldStateChainCursor :one
INSERT INTO world_state_chain_cursors (msgchain_id, revision)
SELECT mc.id, $1::bigint
FROM msgchains mc
WHERE mc.id = $2
  AND (
    $1::bigint = 0
    OR EXISTS (
      SELECT 1 FROM world_state_events e
      WHERE e.revision = $1::bigint AND e.flow_id = mc.flow_id
    )
  )
ON CONFLICT (msgchain_id) DO UPDATE SET revision = EXCLUDED.revision
WHERE world_state_chain_cursors.revision <= EXCLUDED.revision
RETURNING msgchain_id, revision, updated_at
`

type AdvanceWorldStateChainCursorParams struct {
	Revision   int64 `json:"revision"`
	MsgchainID int64 `json:"msgchain_id"`
}

func (q *Queries) AdvanceWorldStateChainCursor(ctx context.Context, arg AdvanceWorldStateChainCursorParams) (WorldStateChainCursor, error) {
	row := q.db.QueryRowContext(ctx, advanceWorldStateChainCursor, arg.Revision, arg.MsgchainID)
	var i WorldStateChainCursor
	err := row.Scan(&i.MsgchainID, &i.Revision, &i.UpdatedAt)
	return i, err
}

const bindAgentTaskUpdateRecipient = `-- name: BindAgentTaskUpdateRecipient :one
UPDATE agent_task_updates atu
SET recipient_msgchain_id = mc.id
FROM msgchains mc
WHERE atu.id = $1
  AND atu.flow_id = $2
  AND atu.state = 'pending'
  AND (atu.recipient_msgchain_id IS NULL OR atu.recipient_msgchain_id = mc.id)
  AND mc.id = $3
  AND mc.flow_id = atu.flow_id
RETURNING atu.id, atu.flow_id, atu.sender_msgchain_id, atu.target_type, atu.target_task_id, atu.target_subtask_id, atu.target_assistant_id, atu.target_role, atu.target_msgchain_id, atu.instruction, atu.selected_facts, atu.source_revisions, atu.state, atu.recipient_msgchain_id, atu.delivered_at, atu.rejected_at, atu.rejection_reason, atu.created_at, atu.updated_at
`

type BindAgentTaskUpdateRecipientParams struct {
	UpdateID            int64 `json:"update_id"`
	FlowID              int64 `json:"flow_id"`
	RecipientMsgchainID int64 `json:"recipient_msgchain_id"`
}

func (q *Queries) BindAgentTaskUpdateRecipient(ctx context.Context, arg BindAgentTaskUpdateRecipientParams) (AgentTaskUpdate, error) {
	row := q.db.QueryRowContext(ctx, bindAgentTaskUpdateRecipient, arg.UpdateID, arg.FlowID, arg.RecipientMsgchainID)
	var i AgentTaskUpdate
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.SenderMsgchainID,
		&i.TargetType,
		&i.TargetTaskID,
		&i.TargetSubtaskID,
		&i.TargetAssistantID,
		&i.TargetRole,
		&i.TargetMsgchainID,
		&i.Instruction,
		&i.SelectedFacts,
		pq.Array(&i.SourceRevisions),
		&i.State,
		&i.RecipientMsgchainID,
		&i.DeliveredAt,
		&i.RejectedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimPrimaryWorldStateResumeForController = `-- name: ClaimPrimaryWorldStateResumeForController :one
UPDATE agent_chain_waits
SET lease_owner = $1, lease_expires_at = $2
WHERE msgchain_id = $3
  AND state = 'resolved'
  AND resolution_winner = 'world_state'
  AND resume_pending = TRUE
RETURNING msgchain_id, flow_id, wait_kind, pending_tool_call_id, state, resolution_winner, resolution_ref, resolved_at, lease_owner, lease_expires_at, retry_count, next_attempt_at, resume_pending, resume_intent, created_at, updated_at
`

type ClaimPrimaryWorldStateResumeForControllerParams struct {
	LeaseOwner     sql.NullString `json:"lease_owner"`
	LeaseExpiresAt sql.NullTime   `json:"lease_expires_at"`
	MsgchainID     int64          `json:"msgchain_id"`
}

func (q *Queries) ClaimPrimaryWorldStateResumeForController(ctx context.Context, arg ClaimPrimaryWorldStateResumeForControllerParams) (AgentChainWait, error) {
	row := q.db.QueryRowContext(ctx, claimPrimaryWorldStateResumeForController, arg.LeaseOwner, arg.LeaseExpiresAt, arg.MsgchainID)
	var i AgentChainWait
	err := row.Scan(
		&i.MsgchainID,
		&i.FlowID,
		&i.WaitKind,
		&i.PendingToolCallID,
		&i.State,
		&i.ResolutionWinner,
		&i.ResolutionRef,
		&i.ResolvedAt,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.RetryCount,
		&i.NextAttemptAt,
		&i.ResumePending,
		&i.ResumeIntent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAgentTaskUpdate = `-- name: CreateAgentTaskUpdate :one
INSERT INTO agent_task_updates (
  flow_id, sender_msgchain_id, target_type, target_task_id, target_subtask_id,
  target_assistant_id, target_role, target_msgchain_id, instruction,
  selected_facts, source_revisions
)
SELECT
  $1, mc.id, $2, $3,
  $4, $5, $6,
  $7, $8, $9,
  $10::bigint[]
FROM msgchains mc
WHERE mc.id = $11 AND mc.flow_id = $1
RETURNING agent_task_updates.id, agent_task_updates.flow_id, agent_task_updates.sender_msgchain_id, agent_task_updates.target_type, agent_task_updates.target_task_id, agent_task_updates.target_subtask_id, agent_task_updates.target_assistant_id, agent_task_updates.target_role, agent_task_updates.target_msgchain_id, agent_task_updates.instruction, agent_task_updates.selected_facts, agent_task_updates.source_revisions, agent_task_updates.state, agent_task_updates.recipient_msgchain_id, agent_task_updates.delivered_at, agent_task_updates.rejected_at, agent_task_updates.rejection_reason, agent_task_updates.created_at, agent_task_updates.updated_at
`

type CreateAgentTaskUpdateParams struct {
	FlowID            int64               `json:"flow_id"`
	TargetType        AgentTaskTargetType `json:"target_type"`
	TargetTaskID      sql.NullInt64       `json:"target_task_id"`
	TargetSubtaskID   sql.NullInt64       `json:"target_subtask_id"`
	TargetAssistantID sql.NullInt64       `json:"target_assistant_id"`
	TargetRole        sql.NullString      `json:"target_role"`
	TargetMsgchainID  sql.NullInt64       `json:"target_msgchain_id"`
	Instruction       string              `json:"instruction"`
	SelectedFacts     json.RawMessage     `json:"selected_facts"`
	SourceRevisions   []int64             `json:"source_revisions"`
	SenderMsgchainID  int64               `json:"sender_msgchain_id"`
}

func (q *Queries) CreateAgentTaskUpdate(ctx context.Context, arg CreateAgentTaskUpdateParams) (AgentTaskUpdate, error) {
	row := q.db.QueryRowContext(ctx, createAgentTaskUpdate,
		arg.FlowID,
		arg.TargetType,
		arg.TargetTaskID,
		arg.TargetSubtaskID,
		arg.TargetAssistantID,
		arg.TargetRole,
		arg.TargetMsgchainID,
		arg.Instruction,
		arg.SelectedFacts,
		pq.Array(arg.SourceRevisions),
		arg.SenderMsgchainID,
	)
	var i AgentTaskUpdate
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.SenderMsgchainID,
		&i.TargetType,
		&i.TargetTaskID,
		&i.TargetSubtaskID,
		&i.TargetAssistantID,
		&i.TargetRole,
		&i.TargetMsgchainID,
		&i.Instruction,
		&i.SelectedFacts,
		pq.Array(&i.SourceRevisions),
		&i.State,
		&i.RecipientMsgchainID,
		&i.DeliveredAt,
		&i.RejectedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorldStateEvent = `-- name: CreateWorldStateEvent :one
INSERT INTO world_state_events (flow_id, kind, facts, actor, actor_msgchain_id, provenance)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING revision, flow_id, kind, facts, actor, actor_msgchain_id, provenance, created_at
`

type CreateWorldStateEventParams struct {
	FlowID          int64               `json:"flow_id"`
	Kind            WorldStateEventKind `json:"kind"`
	Facts           json.RawMessage     `json:"facts"`
	Actor           string              `json:"actor"`
	ActorMsgchainID sql.NullInt64       `json:"actor_msgchain_id"`
	Provenance      json.RawMessage     `json:"provenance"`
}

func (q *Queries) CreateWorldStateEvent(ctx context.Context, arg CreateWorldStateEventParams) (WorldStateEvent, error) {
	row := q.db.QueryRowContext(ctx, createWorldStateEvent,
		arg.FlowID,
		arg.Kind,
		arg.Facts,
		arg.Actor,
		arg.ActorMsgchainID,
		arg.Provenance,
	)
	var i WorldStateEvent
	err := row.Scan(
		&i.Revision,
		&i.FlowID,
		&i.Kind,
		&i.Facts,
		&i.Actor,
		&i.ActorMsgchainID,
		&i.Provenance,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAcceptedPrimaryWorldStateWait = `-- name: DeleteAcceptedPrimaryWorldStateWait :one
DELETE FROM agent_chain_waits
WHERE msgchain_id = $1
  AND state = 'resolved'
  AND resolution_winner = 'world_state'
  AND resume_pending = FALSE
RETURNING msgchain_id, flow_id, wait_kind, pending_tool_call_id, state, resolution_winner, resolution_ref, resolved_at, lease_owner, lease_expires_at, retry_count, next_attempt_at, resume_pending, resume_intent, created_at, updated_at
`

func (q *Queries) DeleteAcceptedPrimaryWorldStateWait(ctx context.Context, msgchainID int64) (AgentChainWait, error) {
	row := q.db.QueryRowContext(ctx, deleteAcceptedPrimaryWorldStateWait, msgchainID)
	var i AgentChainWait
	err := row.Scan(
		&i.MsgchainID,
		&i.FlowID,
		&i.WaitKind,
		&i.PendingToolCallID,
		&i.State,
		&i.ResolutionWinner,
		&i.ResolutionRef,
		&i.ResolvedAt,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.RetryCount,
		&i.NextAttemptAt,
		&i.ResumePending,
		&i.ResumeIntent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgentChainWait = `-- name: DeleteAgentChainWait :exec
DELETE FROM agent_chain_waits WHERE msgchain_id = $1
`

func (q *Queries) DeleteAgentChainWait(ctx context.Context, msgchainID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAgentChainWait, msgchainID)
	return err
}

const getAgentChainWait = `-- name: GetAgentChainWait :one
SELECT msgchain_id, flow_id, wait_kind, pending_tool_call_id, state, resolution_winner, resolution_ref, resolved_at, lease_owner, lease_expires_at, retry_count, next_attempt_at, resume_pending, resume_intent, created_at, updated_at FROM agent_chain_waits WHERE msgchain_id = $1
`

func (q *Queries) GetAgentChainWait(ctx context.Context, msgchainID int64) (AgentChainWait, error) {
	row := q.db.QueryRowContext(ctx, getAgentChainWait, msgchainID)
	var i AgentChainWait
	err := row.Scan(
		&i.MsgchainID,
		&i.FlowID,
		&i.WaitKind,
		&i.PendingToolCallID,
		&i.State,
		&i.ResolutionWinner,
		&i.ResolutionRef,
		&i.ResolvedAt,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.RetryCount,
		&i.NextAttemptAt,
		&i.ResumePending,
		&i.ResumeIntent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentTaskUpdate = `-- name: GetAgentTaskUpdate :one
SELECT id, flow_id, sender_msgchain_id, target_type, target_task_id, target_subtask_id, target_assistant_id, target_role, target_msgchain_id, instruction, selected_facts, source_revisions, state, recipient_msgchain_id, delivered_at, rejected_at, rejection_reason, created_at, updated_at
FROM agent_task_updates
WHERE id = $1 AND flow_id = $2
`

type GetAgentTaskUpdateParams struct {
	ID     int64 `json:"id"`
	FlowID int64 `json:"flow_id"`
}

func (q *Queries) GetAgentTaskUpdate(ctx context.Context, arg GetAgentTaskUpdateParams) (AgentTaskUpdate, error) {
	row := q.db.QueryRowContext(ctx, getAgentTaskUpdate, arg.ID, arg.FlowID)
	var i AgentTaskUpdate
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.SenderMsgchainID,
		&i.TargetType,
		&i.TargetTaskID,
		&i.TargetSubtaskID,
		&i.TargetAssistantID,
		&i.TargetRole,
		&i.TargetMsgchainID,
		&i.Instruction,
		&i.SelectedFacts,
		pq.Array(&i.SourceRevisions),
		&i.State,
		&i.RecipientMsgchainID,
		&i.DeliveredAt,
		&i.RejectedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClaimedPrimaryWorldStateResume = `-- name: GetClaimedPrimaryWorldStateResume :one
SELECT msgchain_id, flow_id, wait_kind, pending_tool_call_id, state, resolution_winner, resolution_ref, resolved_at, lease_owner, lease_expires_at, retry_count, next_attempt_at, resume_pending, resume_intent, created_at, updated_at FROM agent_chain_waits
WHERE msgchain_id = $1
  AND state = 'resolved'
  AND resolution_winner = 'world_state'
  AND pending_tool_call_id = $2
  AND resolution_ref = $3
  AND resume_pending = TRUE
  AND resume_intent = $4
  AND lease_owner = $5
  AND lease_expires_at > CURRENT_TIMESTAMP
`

type GetClaimedPrimaryWorldStateResumeParams struct {
	MsgchainID        int64           `json:"msgchain_id"`
	PendingToolCallID sql.NullString  `json:"pending_tool_call_id"`
	ResolutionRef     sql.NullInt64   `json:"resolution_ref"`
	ResumeIntent      json.RawMessage `json:"resume_intent"`
	LeaseOwner        sql.NullString  `json:"lease_owner"`
}

func (q *Queries) GetClaimedPrimaryWorldStateResume(ctx context.Context, arg GetClaimedPrimaryWorldStateResumeParams) (AgentChainWait, error) {
	row := q.db.QueryRowContext(ctx, getClaimedPrimaryWorldStateResume,
		arg.MsgchainID,
		arg.PendingToolCallID,
		arg.ResolutionRef,
		arg.ResumeIntent,
		arg.LeaseOwner,
	)
	var i AgentChainWait
	err := row.Scan(
		&i.MsgchainID,
		&i.FlowID,
		&i.WaitKind,
		&i.PendingToolCallID,
		&i.State,
		&i.ResolutionWinner,
		&i.ResolutionRef,
		&i.ResolvedAt,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.RetryCount,
		&i.NextAttemptAt,
		&i.ResumePending,
		&i.ResumeIntent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingAgentTaskUpdateHead = `-- name: GetPendingAgentTaskUpdateHead :one
SELECT COALESCE(MAX(atu.id), 0)::bigint
FROM agent_task_updates atu
INNER JOIN msgchains mc ON mc.id = $1 AND mc.flow_id = atu.flow_id
WHERE atu.flow_id = $2 AND atu.recipient_msgchain_id = mc.id AND atu.state = 'pending'
`

type GetPendingAgentTaskUpdateHeadParams struct {
	RecipientMsgchainID int64 `json:"recipient_msgchain_id"`
	FlowID              int64 `json:"flow_id"`
}

func (q *Queries) GetPendingAgentTaskUpdateHead(ctx context.Context, arg GetPendingAgentTaskUpdateHeadParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPendingAgentTaskUpdateHead, arg.RecipientMsgchainID, arg.FlowID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getPendingAgentTaskUpdatesForRecipient = `-- name: GetPendingAgentTaskUpdatesForRecipient :many
SELECT atu.id, atu.flow_id, atu.sender_msgchain_id, atu.target_type, atu.target_task_id, atu.target_subtask_id, atu.target_assistant_id, atu.target_role, atu.target_msgchain_id, atu.instruction, atu.selected_facts, atu.source_revisions, atu.state, atu.recipient_msgchain_id, atu.delivered_at, atu.rejected_at, atu.rejection_reason, atu.created_at, atu.updated_at
FROM agent_task_updates atu
INNER JOIN msgchains mc ON mc.id = $1 AND mc.flow_id = atu.flow_id
WHERE atu.flow_id = $2
  AND atu.recipient_msgchain_id = mc.id
  AND atu.state = 'pending'
  AND atu.id <= $3
ORDER BY atu.id ASC
LIMIT $4
`

type GetPendingAgentTaskUpdatesForRecipientParams struct {
	RecipientMsgchainID int64 `json:"recipient_msgchain_id"`
	FlowID              int64 `json:"flow_id"`
	ThroughID           int64 `json:"through_id"`
	LimitRows           int64 `json:"limit_rows"`
}

func (q *Queries) GetPendingAgentTaskUpdatesForRecipient(ctx context.Context, arg GetPendingAgentTaskUpdatesForRecipientParams) ([]AgentTaskUpdate, error) {
	rows, err := q.db.QueryContext(ctx, getPendingAgentTaskUpdatesForRecipient,
		arg.RecipientMsgchainID,
		arg.FlowID,
		arg.ThroughID,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentTaskUpdate
	for rows.Next() {
		var i AgentTaskUpdate
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.SenderMsgchainID,
			&i.TargetType,
			&i.TargetTaskID,
			&i.TargetSubtaskID,
			&i.TargetAssistantID,
			&i.TargetRole,
			&i.TargetMsgchainID,
			&i.Instruction,
			&i.SelectedFacts,
			pq.Array(&i.SourceRevisions),
			&i.State,
			&i.RecipientMsgchainID,
			&i.DeliveredAt,
			&i.RejectedAt,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingAgentTaskUpdatesForTarget = `-- name: GetPendingAgentTaskUpdatesForTarget :many
SELECT id, flow_id, sender_msgchain_id, target_type, target_task_id, target_subtask_id, target_assistant_id, target_role, target_msgchain_id, instruction, selected_facts, source_revisions, state, recipient_msgchain_id, delivered_at, rejected_at, rejection_reason, created_at, updated_at
FROM agent_task_updates
WHERE flow_id = $1
  AND state = 'pending'
  AND target_type = $2
  AND target_task_id IS NOT DISTINCT FROM $3
  AND target_subtask_id IS NOT DISTINCT FROM $4
  AND target_assistant_id IS NOT DISTINCT FROM $5
  AND target_role IS NOT DISTINCT FROM $6
  AND target_msgchain_id IS NOT DISTINCT FROM $7
ORDER BY id ASC
LIMIT $8
`

type GetPendingAgentTaskUpdatesForTargetParams struct {
	FlowID            int64               `json:"flow_id"`
	TargetType        AgentTaskTargetType `json:"target_type"`
	TargetTaskID      sql.NullInt64       `json:"target_task_id"`
	TargetSubtaskID   sql.NullInt64       `json:"target_subtask_id"`
	TargetAssistantID sql.NullInt64       `json:"target_assistant_id"`
	TargetRole        sql.NullString      `json:"target_role"`
	TargetMsgchainID  sql.NullInt64       `json:"target_msgchain_id"`
	LimitRows         int64               `json:"limit_rows"`
}

func (q *Queries) GetPendingAgentTaskUpdatesForTarget(ctx context.Context, arg GetPendingAgentTaskUpdatesForTargetParams) ([]AgentTaskUpdate, error) {
	rows, err := q.db.QueryContext(ctx, getPendingAgentTaskUpdatesForTarget,
		arg.FlowID,
		arg.TargetType,
		arg.TargetTaskID,
		arg.TargetSubtaskID,
		arg.TargetAssistantID,
		arg.TargetRole,
		arg.TargetMsgchainID,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentTaskUpdate
	for rows.Next() {
		var i AgentTaskUpdate
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.SenderMsgchainID,
			&i.TargetType,
			&i.TargetTaskID,
			&i.TargetSubtaskID,
			&i.TargetAssistantID,
			&i.TargetRole,
			&i.TargetMsgchainID,
			&i.Instruction,
			&i.SelectedFacts,
			pq.Array(&i.SourceRevisions),
			&i.State,
			&i.RecipientMsgchainID,
			&i.DeliveredAt,
			&i.RejectedAt,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSelectedWorldStateEvents = `-- name: GetSelectedWorldStateEvents :many
SELECT revision, flow_id, kind, facts, actor, actor_msgchain_id, provenance, created_at
FROM world_state_events
WHERE flow_id = $1 AND revision = ANY($2::bigint[])
ORDER BY revision ASC
`

type GetSelectedWorldStateEventsParams struct {
	FlowID  int64   `json:"flow_id"`
	Column2 []int64 `json:"column_2"`
}

func (q *Queries) GetSelectedWorldStateEvents(ctx context.Context, arg GetSelectedWorldStateEventsParams) ([]WorldStateEvent, error) {
	rows, err := q.db.QueryContext(ctx, getSelectedWorldStateEvents, arg.FlowID, pq.Array(arg.Column2))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorldStateEvent
	for rows.Next() {
		var i WorldStateEvent
		if err := rows.Scan(
			&i.Revision,
			&i.FlowID,
			&i.Kind,
			&i.Facts,
			&i.Actor,
			&i.ActorMsgchainID,
			&i.Provenance,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorldStateChainCursor = `-- name: GetWorldStateChainCursor :one
SELECT msgchain_id, revision, updated_at
FROM world_state_chain_cursors
WHERE msgchain_id = $1
`

func (q *Queries) GetWorldStateChainCursor(ctx context.Context, msgchainID int64) (WorldStateChainCursor, error) {
	row := q.db.QueryRowContext(ctx, getWorldStateChainCursor, msgchainID)
	var i WorldStateChainCursor
	err := row.Scan(&i.MsgchainID, &i.Revision, &i.UpdatedAt)
	return i, err
}

const getWorldStateEventHead = `-- name: GetWorldStateEventHead :one
SELECT COALESCE(MAX(revision), 0)::bigint
FROM world_state_events
WHERE flow_id = $1
`

func (q *Queries) GetWorldStateEventHead(ctx context.Context, flowID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getWorldStateEventHead, flowID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getWorldStateEventsByRevision = `-- name: GetWorldStateEventsByRevision :many
SELECT revision, flow_id, kind, facts, actor, actor_msgchain_id, provenance, created_at
FROM world_state_events
WHERE flow_id = $1
  AND revision > $2
  AND revision <= $3
ORDER BY revision ASC
LIMIT $4
`

type GetWorldStateEventsByRevisionParams struct {
	FlowID          int64 `json:"flow_id"`
	AfterRevision   int64 `json:"after_revision"`
	ThroughRevision int64 `json:"through_revision"`
	LimitRows       int64 `json:"limit_rows"`
}

func (q *Queries) GetWorldStateEventsByRevision(ctx context.Context, arg GetWorldStateEventsByRevisionParams) ([]WorldStateEvent, error) {
	rows, err := q.db.QueryContext(ctx, getWorldStateEventsByRevision,
		arg.FlowID,
		arg.AfterRevision,
		arg.ThroughRevision,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorldStateEvent
	for rows.Next() {
		var i WorldStateEvent
		if err := rows.Scan(
			&i.Revision,
			&i.FlowID,
			&i.Kind,
			&i.Facts,
			&i.Actor,
			&i.ActorMsgchainID,
			&i.Provenance,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const leaseAgentChainWaits = `-- name: LeaseAgentChainWaits :many
WITH candidates AS (
  SELECT msgchain_id
  FROM agent_chain_waits
  WHERE state = 'pending'
    AND resolution_winner IS NULL
    AND next_attempt_at <= CURRENT_TIMESTAMP
    AND (lease_expires_at IS NULL OR lease_expires_at <= CURRENT_TIMESTAMP)
  ORDER BY next_attempt_at ASC, msgchain_id ASC
  FOR UPDATE SKIP LOCKED
  LIMIT $3
)
UPDATE agent_chain_waits w
SET lease_owner = $1, lease_expires_at = $2
FROM candidates c
WHERE w.msgchain_id = c.msgchain_id
RETURNING w.msgchain_id, w.flow_id, w.wait_kind, w.pending_tool_call_id, w.state, w.resolution_winner, w.resolution_ref, w.resolved_at, w.lease_owner, w.lease_expires_at, w.retry_count, w.next_attempt_at, w.resume_pending, w.resume_intent, w.created_at, w.updated_at
`

type LeaseAgentChainWaitsParams struct {
	LeaseOwner     sql.NullString `json:"lease_owner"`
	LeaseExpiresAt sql.NullTime   `json:"lease_expires_at"`
	LimitRows      int64          `json:"limit_rows"`
}

func (q *Queries) LeaseAgentChainWaits(ctx context.Context, arg LeaseAgentChainWaitsParams) ([]AgentChainWait, error) {
	rows, err := q.db.QueryContext(ctx, leaseAgentChainWaits, arg.LeaseOwner, arg.LeaseExpiresAt, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentChainWait
	for rows.Next() {
		var i AgentChainWait
		if err := rows.Scan(
			&i.MsgchainID,
			&i.FlowID,
			&i.WaitKind,
			&i.PendingToolCallID,
			&i.State,
			&i.ResolutionWinner,
			&i.ResolutionRef,
			&i.ResolvedAt,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.RetryCount,
			&i.NextAttemptAt,
			&i.ResumePending,
			&i.ResumeIntent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const leasePrimaryWorldStateResumeWaits = `-- name: LeasePrimaryWorldStateResumeWaits :many
WITH candidates AS (
  SELECT w.msgchain_id
  FROM agent_chain_waits w
  INNER JOIN msgchains mc ON mc.id = w.msgchain_id AND mc.flow_id = w.flow_id
  INNER JOIN tasks t ON t.id = mc.task_id AND t.flow_id = w.flow_id
  INNER JOIN subtasks s ON s.id = mc.subtask_id AND s.task_id = t.id
  WHERE w.state = 'resolved'
    AND w.resolution_winner = 'world_state'
    AND w.resume_pending = TRUE
    AND mc.type = 'primary_agent'
    AND t.status NOT IN ('finished', 'failed')
    AND s.status NOT IN ('finished', 'failed')
    AND w.next_attempt_at <= CURRENT_TIMESTAMP
    AND (w.lease_expires_at IS NULL OR w.lease_expires_at <= CURRENT_TIMESTAMP)
  ORDER BY w.resolved_at ASC, w.msgchain_id ASC
  FOR UPDATE OF w SKIP LOCKED
  LIMIT $3
)
UPDATE agent_chain_waits w
SET lease_owner = $1, lease_expires_at = $2
FROM candidates c
WHERE w.msgchain_id = c.msgchain_id
RETURNING w.msgchain_id, w.flow_id, w.wait_kind, w.pending_tool_call_id, w.state, w.resolution_winner, w.resolution_ref, w.resolved_at, w.lease_owner, w.lease_expires_at, w.retry_count, w.next_attempt_at, w.resume_pending, w.resume_intent, w.created_at, w.updated_at
`

type LeasePrimaryWorldStateResumeWaitsParams struct {
	LeaseOwner     sql.NullString `json:"lease_owner"`
	LeaseExpiresAt sql.NullTime   `json:"lease_expires_at"`
	LimitRows      int64          `json:"limit_rows"`
}

func (q *Queries) LeasePrimaryWorldStateResumeWaits(ctx context.Context, arg LeasePrimaryWorldStateResumeWaitsParams) ([]AgentChainWait, error) {
	rows, err := q.db.QueryContext(ctx, leasePrimaryWorldStateResumeWaits, arg.LeaseOwner, arg.LeaseExpiresAt, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentChainWait
	for rows.Next() {
		var i AgentChainWait
		if err := rows.Scan(
			&i.MsgchainID,
			&i.FlowID,
			&i.WaitKind,
			&i.PendingToolCallID,
			&i.State,
			&i.ResolutionWinner,
			&i.ResolutionRef,
			&i.ResolvedAt,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.RetryCount,
			&i.NextAttemptAt,
			&i.ResumePending,
			&i.ResumeIntent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const leasePrimaryWorldStateWaits = `-- name: LeasePrimaryWorldStateWaits :many
WITH candidates AS (
  SELECT w.msgchain_id
  FROM agent_chain_waits w
  INNER JOIN msgchains mc ON mc.id = w.msgchain_id AND mc.flow_id = w.flow_id
  INNER JOIN tasks t ON t.id = mc.task_id AND t.flow_id = w.flow_id
  INNER JOIN subtasks s ON s.id = mc.subtask_id AND s.task_id = t.id
  WHERE w.wait_kind = 'tool'
    AND w.state = 'pending'
    AND w.resolution_winner IS NULL
    AND mc.type = 'primary_agent'
    AND t.status NOT IN ('finished', 'failed')
    AND s.status NOT IN ('finished', 'failed')
    AND w.next_attempt_at <= CURRENT_TIMESTAMP
    AND (w.lease_expires_at IS NULL OR w.lease_expires_at <= CURRENT_TIMESTAMP)
    AND COALESCE((SELECT c.revision FROM world_state_chain_cursors c WHERE c.msgchain_id = w.msgchain_id), 0)
      < COALESCE((SELECT MAX(e.revision) FROM world_state_events e WHERE e.flow_id = w.flow_id), 0)
  ORDER BY w.next_attempt_at ASC, w.msgchain_id ASC
  FOR UPDATE OF w SKIP LOCKED
  LIMIT $3
)
UPDATE agent_chain_waits w
SET lease_owner = $1, lease_expires_at = $2
FROM candidates c
WHERE w.msgchain_id = c.msgchain_id
RETURNING w.msgchain_id, w.flow_id, w.wait_kind, w.pending_tool_call_id, w.state, w.resolution_winner, w.resolution_ref, w.resolved_at, w.lease_owner, w.lease_expires_at, w.retry_count, w.next_attempt_at, w.resume_pending, w.resume_intent, w.created_at, w.updated_at
`

type LeasePrimaryWorldStateWaitsParams struct {
	LeaseOwner     sql.NullString `json:"lease_owner"`
	LeaseExpiresAt sql.NullTime   `json:"lease_expires_at"`
	LimitRows      int64          `json:"limit_rows"`
}

func (q *Queries) LeasePrimaryWorldStateWaits(ctx context.Context, arg LeasePrimaryWorldStateWaitsParams) ([]AgentChainWait, error) {
	rows, err := q.db.QueryContext(ctx, leasePrimaryWorldStateWaits, arg.LeaseOwner, arg.LeaseExpiresAt, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentChainWait
	for rows.Next() {
		var i AgentChainWait
		if err := rows.Scan(
			&i.MsgchainID,
			&i.FlowID,
			&i.WaitKind,
			&i.PendingToolCallID,
			&i.State,
			&i.ResolutionWinner,
			&i.ResolutionRef,
			&i.ResolvedAt,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.RetryCount,
			&i.NextAttemptAt,
			&i.ResumePending,
			&i.ResumeIntent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAgentAssistantTargetLifecycle = `-- name: LockAgentAssistantTargetLifecycle :one
SELECT a.id, a.status, a.title, a.model, a.model_provider_name, a.language, a.functions, a.trace_id, a.flow_id, a.use_agents, a.msgchain_id, a.created_at, a.updated_at, a.deleted_at, a.model_provider_type, a.tool_call_id_template
FROM assistants a
WHERE a.id = $1
  AND a.flow_id = $2
  AND a.deleted_at IS NULL
FOR UPDATE
`

type LockAgentAssistantTargetLifecycleParams struct {
	TargetAssistantID int64 `json:"target_assistant_id"`
	FlowID            int64 `json:"flow_id"`
}

func (q *Queries) LockAgentAssistantTargetLifecycle(ctx context.Context, arg LockAgentAssistantTargetLifecycleParams) (Assistant, error) {
	row := q.db.QueryRowContext(ctx, lockAgentAssistantTargetLifecycle, arg.TargetAssistantID, arg.FlowID)
	var i Assistant
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Title,
		&i.Model,
		&i.ModelProviderName,
		&i.Language,
		&i.Functions,
		&i.TraceID,
		&i.FlowID,
		&i.UseAgents,
		&i.MsgchainID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ModelProviderType,
		&i.ToolCallIDTemplate,
	)
	return i, err
}

const lockAgentChainWait = `-- name: LockAgentChainWait :one
SELECT msgchain_id, flow_id, wait_kind, pending_tool_call_id, state, resolution_winner, resolution_ref, resolved_at, lease_owner, lease_expires_at, retry_count, next_attempt_at, resume_pending, resume_intent, created_at, updated_at FROM agent_chain_waits WHERE msgchain_id = $1 FOR UPDATE
`

func (q *Queries) LockAgentChainWait(ctx context.Context, msgchainID int64) (AgentChainWait, error) {
	row := q.db.QueryRowContext(ctx, lockAgentChainWait, msgchainID)
	var i AgentChainWait
	err := row.Scan(
		&i.MsgchainID,
		&i.FlowID,
		&i.WaitKind,
		&i.PendingToolCallID,
		&i.State,
		&i.ResolutionWinner,
		&i.ResolutionRef,
		&i.ResolvedAt,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.RetryCount,
		&i.NextAttemptAt,
		&i.ResumePending,
		&i.ResumeIntent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockAgentSpecialistMsgchain = `-- name: LockAgentSpecialistMsgchain :one
SELECT mc.id, mc.type, mc.model, mc.model_provider, mc.usage_in, mc.usage_out, mc.chain, mc.flow_id, mc.task_id, mc.subtask_id, mc.created_at, mc.updated_at, mc.usage_cache_in, mc.usage_cache_out, mc.usage_cost_in, mc.usage_cost_out, mc.duration_seconds
FROM msgchains mc
WHERE mc.id = $1
  AND mc.flow_id = $2
  AND mc.task_id IS NOT DISTINCT FROM $3
  AND mc.subtask_id IS NOT DISTINCT FROM $4
  AND mc.type::text = $5
FOR UPDATE
`

type LockAgentSpecialistMsgchainParams struct {
	TargetMsgchainID int64         `json:"target_msgchain_id"`
	FlowID           int64         `json:"flow_id"`
	TargetTaskID     sql.NullInt64 `json:"target_task_id"`
	TargetSubtaskID  sql.NullInt64 `json:"target_subtask_id"`
	TargetRole       string        `json:"target_role"`
}

// Specialist routing also locks the task/subtask lifecycle row above. When a
// persisted invocation is selected, this additionally validates and locks it.
func (q *Queries) LockAgentSpecialistMsgchain(ctx context.Context, arg LockAgentSpecialistMsgchainParams) (Msgchain, error) {
	row := q.db.QueryRowContext(ctx, lockAgentSpecialistMsgchain,
		arg.TargetMsgchainID,
		arg.FlowID,
		arg.TargetTaskID,
		arg.TargetSubtaskID,
		arg.TargetRole,
	)
	var i Msgchain
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Model,
		&i.ModelProvider,
		&i.UsageIn,
		&i.UsageOut,
		&i.Chain,
		&i.FlowID,
		&i.TaskID,
		&i.SubtaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UsageCacheIn,
		&i.UsageCacheOut,
		&i.UsageCostIn,
		&i.UsageCostOut,
		&i.DurationSeconds,
	)
	return i, err
}

const lockAgentSubtaskTargetLifecycle = `-- name: LockAgentSubtaskTargetLifecycle :one
SELECT s.id, s.status, s.title, s.description, s.result, s.task_id, s.created_at, s.updated_at, s.context
FROM subtasks s
INNER JOIN tasks t ON t.id = s.task_id
WHERE s.id = $1
  AND t.id = $2
  AND t.flow_id = $3
FOR UPDATE OF s
`

type LockAgentSubtaskTargetLifecycleParams struct {
	TargetSubtaskID int64 `json:"target_subtask_id"`
	TargetTaskID    int64 `json:"target_task_id"`
	FlowID          int64 `json:"flow_id"`
}

func (q *Queries) LockAgentSubtaskTargetLifecycle(ctx context.Context, arg LockAgentSubtaskTargetLifecycleParams) (Subtask, error) {
	row := q.db.QueryRowContext(ctx, lockAgentSubtaskTargetLifecycle, arg.TargetSubtaskID, arg.TargetTaskID, arg.FlowID)
	var i Subtask
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.Result,
		&i.TaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Context,
	)
	return i, err
}

const lockAgentTaskTargetLifecycle = `-- name: LockAgentTaskTargetLifecycle :one
SELECT t.id, t.status, t.title, t.input, t.result, t.flow_id, t.created_at, t.updated_at
FROM tasks t
WHERE t.id = $1 AND t.flow_id = $2
FOR UPDATE
`

type LockAgentTaskTargetLifecycleParams struct {
	TargetTaskID int64 `json:"target_task_id"`
	FlowID       int64 `json:"flow_id"`
}

// Routing and terminal completion must call the matching lifecycle lock first,
// then insert or run the guarded terminal update in the same transaction.
func (q *Queries) LockAgentTaskTargetLifecycle(ctx context.Context, arg LockAgentTaskTargetLifecycleParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, lockAgentTaskTargetLifecycle, arg.TargetTaskID, arg.FlowID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Title,
		&i.Input,
		&i.Result,
		&i.FlowID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockPendingAgentTaskUpdatesForTarget = `-- name: LockPendingAgentTaskUpdatesForTarget :many
SELECT id, flow_id, sender_msgchain_id, target_type, target_task_id, target_subtask_id, target_assistant_id, target_role, target_msgchain_id, instruction, selected_facts, source_revisions, state, recipient_msgchain_id, delivered_at, rejected_at, rejection_reason, created_at, updated_at
FROM agent_task_updates
WHERE flow_id = $1
  AND state = 'pending'
  AND target_type = $2
  AND target_task_id IS NOT DISTINCT FROM $3
  AND target_subtask_id IS NOT DISTINCT FROM $4
  AND target_assistant_id IS NOT DISTINCT FROM $5
  AND target_role IS NOT DISTINCT FROM $6
  AND target_msgchain_id IS NOT DISTINCT FROM $7
ORDER BY id ASC
FOR UPDATE
`

type LockPendingAgentTaskUpdatesForTargetParams struct {
	FlowID            int64               `json:"flow_id"`
	TargetType        AgentTaskTargetType `json:"target_type"`
	TargetTaskID      sql.NullInt64       `json:"target_task_id"`
	TargetSubtaskID   sql.NullInt64       `json:"target_subtask_id"`
	TargetAssistantID sql.NullInt64       `json:"target_assistant_id"`
	TargetRole        sql.NullString      `json:"target_role"`
	TargetMsgchainID  sql.NullInt64       `json:"target_msgchain_id"`
}

func (q *Queries) LockPendingAgentTaskUpdatesForTarget(ctx context.Context, arg LockPendingAgentTaskUpdatesForTargetParams) ([]AgentTaskUpdate, error) {
	rows, err := q.db.QueryContext(ctx, lockPendingAgentTaskUpdatesForTarget,
		arg.FlowID,
		arg.TargetType,
		arg.TargetTaskID,
		arg.TargetSubtaskID,
		arg.TargetAssistantID,
		arg.TargetRole,
		arg.TargetMsgchainID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentTaskUpdate
	for rows.Next() {
		var i AgentTaskUpdate
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.SenderMsgchainID,
			&i.TargetType,
			&i.TargetTaskID,
			&i.TargetSubtaskID,
			&i.TargetAssistantID,
			&i.TargetRole,
			&i.TargetMsgchainID,
			&i.Instruction,
			&i.SelectedFacts,
			pq.Array(&i.SourceRevisions),
			&i.State,
			&i.RecipientMsgchainID,
			&i.DeliveredAt,
			&i.RejectedAt,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectAgentTaskUpdate = `-- name: RejectAgentTaskUpdate :one
UPDATE agent_task_updates
SET state = 'rejected', rejected_at = $1, rejection_reason = $2
WHERE id = $3 AND flow_id = $4 AND state = 'pending'
RETURNING id, flow_id, sender_msgchain_id, target_type, target_task_id, target_subtask_id, target_assistant_id, target_role, target_msgchain_id, instruction, selected_facts, source_revisions, state, recipient_msgchain_id, delivered_at, rejected_at, rejection_reason, created_at, updated_at
`

type RejectAgentTaskUpdateParams struct {
	RejectedAt      sql.NullTime   `json:"rejected_at"`
	RejectionReason sql.NullString `json:"rejection_reason"`
	UpdateID        int64          `json:"update_id"`
	FlowID          int64          `json:"flow_id"`
}

func (q *Queries) RejectAgentTaskUpdate(ctx context.Context, arg RejectAgentTaskUpdateParams) (AgentTaskUpdate, error) {
	row := q.db.QueryRowContext(ctx, rejectAgentTaskUpdate,
		arg.RejectedAt,
		arg.RejectionReason,
		arg.UpdateID,
		arg.FlowID,
	)
	var i AgentTaskUpdate
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.SenderMsgchainID,
		&i.TargetType,
		&i.TargetTaskID,
		&i.TargetSubtaskID,
		&i.TargetAssistantID,
		&i.TargetRole,
		&i.TargetMsgchainID,
		&i.Instruction,
		&i.SelectedFacts,
		pq.Array(&i.SourceRevisions),
		&i.State,
		&i.RecipientMsgchainID,
		&i.DeliveredAt,
		&i.RejectedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rejectPendingAgentTaskUpdatesForTarget = `-- name: RejectPendingAgentTaskUpdatesForTarget :many
UPDATE agent_task_updates
SET state = 'rejected', rejected_at = $1, rejection_reason = $2
WHERE flow_id = $3
  AND state = 'pending'
  AND target_type = $4
  AND target_task_id IS NOT DISTINCT FROM $5
  AND target_subtask_id IS NOT DISTINCT FROM $6
  AND target_assistant_id IS NOT DISTINCT FROM $7
  AND target_role IS NOT DISTINCT FROM $8
  AND target_msgchain_id IS NOT DISTINCT FROM $9
RETURNING id, flow_id, sender_msgchain_id, target_type, target_task_id, target_subtask_id, target_assistant_id, target_role, target_msgchain_id, instruction, selected_facts, source_revisions, state, recipient_msgchain_id, delivered_at, rejected_at, rejection_reason, created_at, updated_at
`

type RejectPendingAgentTaskUpdatesForTargetParams struct {
	RejectedAt        sql.NullTime        `json:"rejected_at"`
	RejectionReason   sql.NullString      `json:"rejection_reason"`
	FlowID            int64               `json:"flow_id"`
	TargetType        AgentTaskTargetType `json:"target_type"`
	TargetTaskID      sql.NullInt64       `json:"target_task_id"`
	TargetSubtaskID   sql.NullInt64       `json:"target_subtask_id"`
	TargetAssistantID sql.NullInt64       `json:"target_assistant_id"`
	TargetRole        sql.NullString      `json:"target_role"`
	TargetMsgchainID  sql.NullInt64       `json:"target_msgchain_id"`
}

func (q *Queries) RejectPendingAgentTaskUpdatesForTarget(ctx context.Context, arg RejectPendingAgentTaskUpdatesForTargetParams) ([]AgentTaskUpdate, error) {
	rows, err := q.db.QueryContext(ctx, rejectPendingAgentTaskUpdatesForTarget,
		arg.RejectedAt,
		arg.RejectionReason,
		arg.FlowID,
		arg.TargetType,
		arg.TargetTaskID,
		arg.TargetSubtaskID,
		arg.TargetAssistantID,
		arg.TargetRole,
		arg.TargetMsgchainID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentTaskUpdate
	for rows.Next() {
		var i AgentTaskUpdate
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.SenderMsgchainID,
			&i.TargetType,
			&i.TargetTaskID,
			&i.TargetSubtaskID,
			&i.TargetAssistantID,
			&i.TargetRole,
			&i.TargetMsgchainID,
			&i.Instruction,
			&i.SelectedFacts,
			pq.Array(&i.SourceRevisions),
			&i.State,
			&i.RecipientMsgchainID,
			&i.DeliveredAt,
			&i.RejectedAt,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseAgentChainWaitLease = `-- name: ReleaseAgentChainWaitLease :one
UPDATE agent_chain_waits
SET lease_owner = NULL,
    lease_expires_at = NULL,
    retry_count = retry_count + 1,
    next_attempt_at = $1
WHERE msgchain_id = $2
  AND state = 'pending'
  AND resolution_winner IS NULL
  AND lease_owner = $3
RETURNING msgchain_id, flow_id, wait_kind, pending_tool_call_id, state, resolution_winner, resolution_ref, resolved_at, lease_owner, lease_expires_at, retry_count, next_attempt_at, resume_pending, resume_intent, created_at, updated_at
`

type ReleaseAgentChainWaitLeaseParams struct {
	NextAttemptAt time.Time      `json:"next_attempt_at"`
	MsgchainID    int64          `json:"msgchain_id"`
	LeaseOwner    sql.NullString `json:"lease_owner"`
}

func (q *Queries) ReleaseAgentChainWaitLease(ctx context.Context, arg ReleaseAgentChainWaitLeaseParams) (AgentChainWait, error) {
	row := q.db.QueryRowContext(ctx, releaseAgentChainWaitLease, arg.NextAttemptAt, arg.MsgchainID, arg.LeaseOwner)
	var i AgentChainWait
	err := row.Scan(
		&i.MsgchainID,
		&i.FlowID,
		&i.WaitKind,
		&i.PendingToolCallID,
		&i.State,
		&i.ResolutionWinner,
		&i.ResolutionRef,
		&i.ResolvedAt,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.RetryCount,
		&i.NextAttemptAt,
		&i.ResumePending,
		&i.ResumeIntent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releasePrimaryWorldStateResumeLease = `-- name: ReleasePrimaryWorldStateResumeLease :one
UPDATE agent_chain_waits
SET lease_owner = NULL,
    lease_expires_at = NULL,
    retry_count = retry_count + 1,
    next_attempt_at = $1
WHERE msgchain_id = $2
  AND state = 'resolved'
  AND resolution_winner = 'world_state'
  AND resume_pending = TRUE
  AND lease_owner = $3
RETURNING msgchain_id, flow_id, wait_kind, pending_tool_call_id, state, resolution_winner, resolution_ref, resolved_at, lease_owner, lease_expires_at, retry_count, next_attempt_at, resume_pending, resume_intent, created_at, updated_at
`

type ReleasePrimaryWorldStateResumeLeaseParams struct {
	NextAttemptAt time.Time      `json:"next_attempt_at"`
	MsgchainID    int64          `json:"msgchain_id"`
	LeaseOwner    sql.NullString `json:"lease_owner"`
}

func (q *Queries) ReleasePrimaryWorldStateResumeLease(ctx context.Context, arg ReleasePrimaryWorldStateResumeLeaseParams) (AgentChainWait, error) {
	row := q.db.QueryRowContext(ctx, releasePrimaryWorldStateResumeLease, arg.NextAttemptAt, arg.MsgchainID, arg.LeaseOwner)
	var i AgentChainWait
	err := row.Scan(
		&i.MsgchainID,
		&i.FlowID,
		&i.WaitKind,
		&i.PendingToolCallID,
		&i.State,
		&i.ResolutionWinner,
		&i.ResolutionRef,
		&i.ResolvedAt,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.RetryCount,
		&i.NextAttemptAt,
		&i.ResumePending,
		&i.ResumeIntent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const renewAgentChainWaitLease = `-- name: RenewAgentChainWaitLease :one
UPDATE agent_chain_waits
SET lease_expires_at = $1
WHERE msgchain_id = $2
  AND state = 'pending'
  AND resolution_winner IS NULL
  AND lease_owner = $3
  AND lease_expires_at > CURRENT_TIMESTAMP
RETURNING msgchain_id, flow_id, wait_kind, pending_tool_call_id, state, resolution_winner, resolution_ref, resolved_at, lease_owner, lease_expires_at, retry_count, next_attempt_at, resume_pending, resume_intent, created_at, updated_at
`

type RenewAgentChainWaitLeaseParams struct {
	LeaseExpiresAt sql.NullTime   `json:"lease_expires_at"`
	MsgchainID     int64          `json:"msgchain_id"`
	LeaseOwner     sql.NullString `json:"lease_owner"`
}

func (q *Queries) RenewAgentChainWaitLease(ctx context.Context, arg RenewAgentChainWaitLeaseParams) (AgentChainWait, error) {
	row := q.db.QueryRowContext(ctx, renewAgentChainWaitLease, arg.LeaseExpiresAt, arg.MsgchainID, arg.LeaseOwner)
	var i AgentChainWait
	err := row.Scan(
		&i.MsgchainID,
		&i.FlowID,
		&i.WaitKind,
		&i.PendingToolCallID,
		&i.State,
		&i.ResolutionWinner,
		&i.ResolutionRef,
		&i.ResolvedAt,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.RetryCount,
		&i.NextAttemptAt,
		&i.ResumePending,
		&i.ResumeIntent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveAgentChainWait = `-- name: ResolveAgentChainWait :one
UPDATE agent_chain_waits w
SET state = 'resolved',
    resolution_winner = $1,
    resolution_ref = $2,
    resolved_at = $3,
    lease_owner = NULL,
    lease_expires_at = NULL,
    resume_pending = $4,
    resume_intent = $5
WHERE w.msgchain_id = $6
  AND w.state = 'pending'
  AND w.resolution_winner IS NULL
  AND (
    $1::text <> 'world_state'
    OR EXISTS (
      SELECT 1 FROM world_state_events e
      WHERE e.revision = $2 AND e.flow_id = w.flow_id
    )
  )
  AND (
    $1::text <> 'task_update'
    OR EXISTS (
      SELECT 1 FROM agent_task_updates atu
      WHERE atu.id = $2 AND atu.flow_id = w.flow_id AND atu.state = 'pending'
    )
  )
RETURNING w.msgchain_id, w.flow_id, w.wait_kind, w.pending_tool_call_id, w.state, w.resolution_winner, w.resolution_ref, w.resolved_at, w.lease_owner, w.lease_expires_at, w.retry_count, w.next_attempt_at, w.resume_pending, w.resume_intent, w.created_at, w.updated_at
`

type ResolveAgentChainWaitParams struct {
	ResolutionWinner sql.NullString  `json:"resolution_winner"`
	ResolutionRef    sql.NullInt64   `json:"resolution_ref"`
	ResolvedAt       sql.NullTime    `json:"resolved_at"`
	ResumePending    bool            `json:"resume_pending"`
	ResumeIntent     json.RawMessage `json:"resume_intent"`
	MsgchainID       int64           `json:"msgchain_id"`
}

func (q *Queries) ResolveAgentChainWait(ctx context.Context, arg ResolveAgentChainWaitParams) (AgentChainWait, error) {
	row := q.db.QueryRowContext(ctx, resolveAgentChainWait,
		arg.ResolutionWinner,
		arg.ResolutionRef,
		arg.ResolvedAt,
		arg.ResumePending,
		arg.ResumeIntent,
		arg.MsgchainID,
	)
	var i AgentChainWait
	err := row.Scan(
		&i.MsgchainID,
		&i.FlowID,
		&i.WaitKind,
		&i.PendingToolCallID,
		&i.State,
		&i.ResolutionWinner,
		&i.ResolutionRef,
		&i.ResolvedAt,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.RetryCount,
		&i.NextAttemptAt,
		&i.ResumePending,
		&i.ResumeIntent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveLeasedPrimaryWorldStateWait = `-- name: ResolveLeasedPrimaryWorldStateWait :one
UPDATE agent_chain_waits w
SET state = 'resolved',
    resolution_winner = 'world_state',
    resolution_ref = $1,
    resolved_at = $2,
    lease_owner = NULL,
    lease_expires_at = NULL,
    resume_pending = TRUE,
    resume_intent = $3
FROM msgchains mc, tasks t, subtasks s
WHERE w.msgchain_id = $4
  AND w.state = 'pending'
  AND w.resolution_winner IS NULL
  AND w.lease_owner = $5
  AND mc.id = w.msgchain_id
  AND mc.flow_id = w.flow_id
  AND mc.type = 'primary_agent'
  AND t.id = mc.task_id
  AND t.flow_id = w.flow_id
  AND t.status NOT IN ('finished', 'failed')
  AND s.id = mc.subtask_id
  AND s.task_id = t.id
  AND s.status NOT IN ('finished', 'failed')
  AND EXISTS (
    SELECT 1 FROM world_state_events e
    WHERE e.flow_id = w.flow_id AND e.revision = $1
  )
  AND COALESCE((SELECT c.revision FROM world_state_chain_cursors c WHERE c.msgchain_id = w.msgchain_id), 0)
    < $1
RETURNING w.msgchain_id, w.flow_id, w.wait_kind, w.pending_tool_call_id, w.state, w.resolution_winner, w.resolution_ref, w.resolved_at, w.lease_owner, w.lease_expires_at, w.retry_count, w.next_attempt_at, w.resume_pending, w.resume_intent, w.created_at, w.updated_at
`

type ResolveLeasedPrimaryWorldStateWaitParams struct {
	ResolutionRef sql.NullInt64   `json:"resolution_ref"`
	ResolvedAt    sql.NullTime    `json:"resolved_at"`
	ResumeIntent  json.RawMessage `json:"resume_intent"`
	MsgchainID    int64           `json:"msgchain_id"`
	LeaseOwner    sql.NullString  `json:"lease_owner"`
}

func (q *Queries) ResolveLeasedPrimaryWorldStateWait(ctx context.Context, arg ResolveLeasedPrimaryWorldStateWaitParams) (AgentChainWait, error) {
	row := q.db.QueryRowContext(ctx, resolveLeasedPrimaryWorldStateWait,
		arg.ResolutionRef,
		arg.ResolvedAt,
		arg.ResumeIntent,
		arg.MsgchainID,
		arg.LeaseOwner,
	)
	var i AgentChainWait
	err := row.Scan(
		&i.MsgchainID,
		&i.FlowID,
		&i.WaitKind,
		&i.PendingToolCallID,
		&i.State,
		&i.ResolutionWinner,
		&i.ResolutionRef,
		&i.ResolvedAt,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.RetryCount,
		&i.NextAttemptAt,
		&i.ResumePending,
		&i.ResumeIntent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const trySetAgentAssistantTargetTerminal = `-- name: TrySetAgentAssistantTargetTerminal :one
UPDATE assistants a
SET status = $1::assistant_status
WHERE a.id = $2
  AND a.flow_id = $3
  AND a.deleted_at IS NULL
  AND $1::text IN ('finished', 'failed')
  AND NOT EXISTS (
    SELECT 1 FROM agent_task_updates atu
    WHERE atu.flow_id = a.flow_id
      AND atu.target_assistant_id = a.id
      AND atu.state = 'pending'
      AND atu.target_type = 'assistant'
  )
RETURNING a.id, a.status, a.title, a.model, a.model_provider_name, a.language, a.functions, a.trace_id, a.flow_id, a.use_agents, a.msgchain_id, a.created_at, a.updated_at, a.deleted_at, a.model_provider_type, a.tool_call_id_template
`

type TrySetAgentAssistantTargetTerminalParams struct {
	Status            AssistantStatus `json:"status"`
	TargetAssistantID int64           `json:"target_assistant_id"`
	FlowID            int64           `json:"flow_id"`
}

func (q *Queries) TrySetAgentAssistantTargetTerminal(ctx context.Context, arg TrySetAgentAssistantTargetTerminalParams) (Assistant, error) {
	row := q.db.QueryRowContext(ctx, trySetAgentAssistantTargetTerminal, arg.Status, arg.TargetAssistantID, arg.FlowID)
	var i Assistant
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Title,
		&i.Model,
		&i.ModelProviderName,
		&i.Language,
		&i.Functions,
		&i.TraceID,
		&i.FlowID,
		&i.UseAgents,
		&i.MsgchainID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ModelProviderType,
		&i.ToolCallIDTemplate,
	)
	return i, err
}

const trySetAgentSubtaskTargetTerminal = `-- name: TrySetAgentSubtaskTargetTerminal :one
UPDATE subtasks s
SET status = $1::subtask_status
FROM tasks t
WHERE s.id = $2
  AND t.id = s.task_id
  AND t.id = $3
  AND t.flow_id = $4
  AND $1::text IN ('finished', 'failed')
  AND NOT EXISTS (
    SELECT 1 FROM agent_task_updates atu
    WHERE atu.flow_id = t.flow_id
      AND atu.target_task_id = t.id
      AND atu.target_subtask_id = s.id
      AND atu.state = 'pending'
      AND atu.target_type IN ('subtask', 'specialist')
  )
RETURNING s.id, s.status, s.title, s.description, s.result, s.task_id, s.created_at, s.updated_at, s.context
`

type TrySetAgentSubtaskTargetTerminalParams struct {
	Status          SubtaskStatus `json:"status"`
	TargetSubtaskID int64         `json:"target_subtask_id"`
	TargetTaskID    int64         `json:"target_task_id"`
	FlowID          int64         `json:"flow_id"`
}

func (q *Queries) TrySetAgentSubtaskTargetTerminal(ctx context.Context, arg TrySetAgentSubtaskTargetTerminalParams) (Subtask, error) {
	row := q.db.QueryRowContext(ctx, trySetAgentSubtaskTargetTerminal,
		arg.Status,
		arg.TargetSubtaskID,
		arg.TargetTaskID,
		arg.FlowID,
	)
	var i Subtask
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.Result,
		&i.TaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Context,
	)
	return i, err
}

const trySetAgentTaskTargetTerminal = `-- name: TrySetAgentTaskTargetTerminal :one
UPDATE tasks t
SET status = $1::task_status
WHERE t.id = $2
  AND t.flow_id = $3
  AND $1::text IN ('finished', 'failed')
  AND NOT EXISTS (
    SELECT 1 FROM agent_task_updates atu
    WHERE atu.flow_id = t.flow_id
      AND atu.target_task_id = t.id
      AND atu.target_subtask_id IS NULL
      AND atu.state = 'pending'
      AND atu.target_type IN ('task', 'specialist')
  )
RETURNING t.id, t.status, t.title, t.input, t.result, t.flow_id, t.created_at, t.updated_at
`

type TrySetAgentTaskTargetTerminalParams struct {
	Status       TaskStatus `json:"status"`
	TargetTaskID int64      `json:"target_task_id"`
	FlowID       int64      `json:"flow_id"`
}

func (q *Queries) TrySetAgentTaskTargetTerminal(ctx context.Context, arg TrySetAgentTaskTargetTerminalParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, trySetAgentTaskTargetTerminal, arg.Status, arg.TargetTaskID, arg.FlowID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Title,
		&i.Input,
		&i.Result,
		&i.FlowID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAgentChainWait = `-- name: UpsertAgentChainWait :one
INSERT INTO agent_chain_waits (flow_id, msgchain_id, wait_kind, pending_tool_call_id)
SELECT mc.flow_id, mc.id, $1, $2
FROM msgchains mc
WHERE mc.id = $3 AND mc.flow_id = $4
ON CONFLICT (msgchain_id) DO UPDATE SET
  msgchain_id = agent_chain_waits.msgchain_id
WHERE agent_chain_waits.state = 'pending'
  AND agent_chain_waits.resolution_winner IS NULL
  AND agent_chain_waits.wait_kind = EXCLUDED.wait_kind
  AND agent_chain_waits.pending_tool_call_id IS NOT DISTINCT FROM EXCLUDED.pending_tool_call_id
RETURNING msgchain_id, flow_id, wait_kind, pending_tool_call_id, state, resolution_winner, resolution_ref, resolved_at, lease_owner, lease_expires_at, retry_count, next_attempt_at, resume_pending, resume_intent, created_at, updated_at
`

type UpsertAgentChainWaitParams struct {
	WaitKind          AgentChainWaitKind `json:"wait_kind"`
	PendingToolCallID sql.NullString     `json:"pending_tool_call_id"`
	MsgchainID        int64              `json:"msgchain_id"`
	FlowID            int64              `json:"flow_id"`
}

func (q *Queries) UpsertAgentChainWait(ctx context.Context, arg UpsertAgentChainWaitParams) (AgentChainWait, error) {
	row := q.db.QueryRowContext(ctx, upsertAgentChainWait,
		arg.WaitKind,
		arg.PendingToolCallID,
		arg.MsgchainID,
		arg.FlowID,
	)
	var i AgentChainWait
	err := row.Scan(
		&i.MsgchainID,
		&i.FlowID,
		&i.WaitKind,
		&i.PendingToolCallID,
		&i.State,
		&i.ResolutionWinner,
		&i.ResolutionRef,
		&i.ResolvedAt,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.RetryCount,
		&i.NextAttemptAt,
		&i.ResumePending,
		&i.ResumeIntent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
