// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: world_state.sql

package database

import (
	"context"
	"encoding/json"
	"time"
)

const createWorldStateTransition = `-- name: CreateWorldStateTransition :one
INSERT INTO world_state_transitions (
  entity_id,
  from_state,
  to_state,
  agent,
  evidence
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, entity_id, from_state, to_state, agent, evidence, created_at
`

type CreateWorldStateTransitionParams struct {
	EntityID  int64               `json:"entity_id"`
	FromState WorldStateLifecycle `json:"from_state"`
	ToState   WorldStateLifecycle `json:"to_state"`
	Agent     string              `json:"agent"`
	Evidence  json.RawMessage     `json:"evidence"`
}

func (q *Queries) CreateWorldStateTransition(ctx context.Context, arg CreateWorldStateTransitionParams) (WorldStateTransition, error) {
	row := q.db.QueryRowContext(ctx, createWorldStateTransition,
		arg.EntityID,
		arg.FromState,
		arg.ToState,
		arg.Agent,
		arg.Evidence,
	)
	var i WorldStateTransition
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.FromState,
		&i.ToState,
		&i.Agent,
		&i.Evidence,
		&i.CreatedAt,
	)
	return i, err
}

const getWorldStateEntitiesByFlow = `-- name: GetWorldStateEntitiesByFlow :many
SELECT id, flow_id, entity_key, type, state, properties, annotations, version, created_at, updated_at
FROM world_state_entities
WHERE flow_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) GetWorldStateEntitiesByFlow(ctx context.Context, flowID int64) ([]WorldStateEntity, error) {
	rows, err := q.db.QueryContext(ctx, getWorldStateEntitiesByFlow, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorldStateEntity
	for rows.Next() {
		var i WorldStateEntity
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.EntityKey,
			&i.Type,
			&i.State,
			&i.Properties,
			&i.Annotations,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorldStateEntityByID = `-- name: GetWorldStateEntityByID :one
SELECT id, flow_id, entity_key, type, state, properties, annotations, version, created_at, updated_at
FROM world_state_entities
WHERE id = $1
`

func (q *Queries) GetWorldStateEntityByID(ctx context.Context, id int64) (WorldStateEntity, error) {
	row := q.db.QueryRowContext(ctx, getWorldStateEntityByID, id)
	var i WorldStateEntity
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.EntityKey,
		&i.Type,
		&i.State,
		&i.Properties,
		&i.Annotations,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorldStateEntityByKey = `-- name: GetWorldStateEntityByKey :one
SELECT id, flow_id, entity_key, type, state, properties, annotations, version, created_at, updated_at
FROM world_state_entities
WHERE flow_id = $1 AND entity_key = $2
`

type GetWorldStateEntityByKeyParams struct {
	FlowID    int64  `json:"flow_id"`
	EntityKey string `json:"entity_key"`
}

func (q *Queries) GetWorldStateEntityByKey(ctx context.Context, arg GetWorldStateEntityByKeyParams) (WorldStateEntity, error) {
	row := q.db.QueryRowContext(ctx, getWorldStateEntityByKey, arg.FlowID, arg.EntityKey)
	var i WorldStateEntity
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.EntityKey,
		&i.Type,
		&i.State,
		&i.Properties,
		&i.Annotations,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorldStateLinksByFlow = `-- name: GetWorldStateLinksByFlow :many
SELECT id, flow_id, source_id, target_id, type, properties, created_at
FROM world_state_links
WHERE flow_id = $1
ORDER BY id ASC
`

func (q *Queries) GetWorldStateLinksByFlow(ctx context.Context, flowID int64) ([]WorldStateLink, error) {
	rows, err := q.db.QueryContext(ctx, getWorldStateLinksByFlow, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorldStateLink
	for rows.Next() {
		var i WorldStateLink
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.SourceID,
			&i.TargetID,
			&i.Type,
			&i.Properties,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorldStateTransitionsByEntity = `-- name: GetWorldStateTransitionsByEntity :many
SELECT id, entity_id, from_state, to_state, agent, evidence, created_at
FROM world_state_transitions
WHERE entity_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetWorldStateTransitionsByEntity(ctx context.Context, entityID int64) ([]WorldStateTransition, error) {
	rows, err := q.db.QueryContext(ctx, getWorldStateTransitionsByEntity, entityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorldStateTransition
	for rows.Next() {
		var i WorldStateTransition
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.FromState,
			&i.ToState,
			&i.Agent,
			&i.Evidence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorldStateTransitionsByFlow = `-- name: GetWorldStateTransitionsByFlow :many
SELECT
  t.id,
  t.entity_id,
  t.from_state,
  t.to_state,
  t.agent,
  t.evidence,
  t.created_at,
  e.entity_key,
  e.type AS entity_type
FROM world_state_transitions t
INNER JOIN world_state_entities e ON e.id = t.entity_id
WHERE e.flow_id = $1
ORDER BY t.created_at DESC
LIMIT $2
`

type GetWorldStateTransitionsByFlowParams struct {
	FlowID int64 `json:"flow_id"`
	Limit  int64 `json:"limit"`
}

type GetWorldStateTransitionsByFlowRow struct {
	ID         int64               `json:"id"`
	EntityID   int64               `json:"entity_id"`
	FromState  WorldStateLifecycle `json:"from_state"`
	ToState    WorldStateLifecycle `json:"to_state"`
	Agent      string              `json:"agent"`
	Evidence   json.RawMessage     `json:"evidence"`
	CreatedAt  time.Time           `json:"created_at"`
	EntityKey  string              `json:"entity_key"`
	EntityType string              `json:"entity_type"`
}

func (q *Queries) GetWorldStateTransitionsByFlow(ctx context.Context, arg GetWorldStateTransitionsByFlowParams) ([]GetWorldStateTransitionsByFlowRow, error) {
	rows, err := q.db.QueryContext(ctx, getWorldStateTransitionsByFlow, arg.FlowID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWorldStateTransitionsByFlowRow
	for rows.Next() {
		var i GetWorldStateTransitionsByFlowRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.FromState,
			&i.ToState,
			&i.Agent,
			&i.Evidence,
			&i.CreatedAt,
			&i.EntityKey,
			&i.EntityType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertWorldStateEntity = `-- name: InsertWorldStateEntity :one
INSERT INTO world_state_entities (
  flow_id,
  entity_key,
  type,
  state,
  properties,
  annotations
) VALUES (
  $1, $2, $3, $4, $5, $6
)
ON CONFLICT (flow_id, entity_key) DO NOTHING
RETURNING id, flow_id, entity_key, type, state, properties, annotations, version, created_at, updated_at
`

type InsertWorldStateEntityParams struct {
	FlowID      int64               `json:"flow_id"`
	EntityKey   string              `json:"entity_key"`
	Type        string              `json:"type"`
	State       WorldStateLifecycle `json:"state"`
	Properties  json.RawMessage     `json:"properties"`
	Annotations json.RawMessage     `json:"annotations"`
}

func (q *Queries) InsertWorldStateEntity(ctx context.Context, arg InsertWorldStateEntityParams) (WorldStateEntity, error) {
	row := q.db.QueryRowContext(ctx, insertWorldStateEntity,
		arg.FlowID,
		arg.EntityKey,
		arg.Type,
		arg.State,
		arg.Properties,
		arg.Annotations,
	)
	var i WorldStateEntity
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.EntityKey,
		&i.Type,
		&i.State,
		&i.Properties,
		&i.Annotations,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWorldStateLink = `-- name: InsertWorldStateLink :one
INSERT INTO world_state_links (
  flow_id,
  source_id,
  target_id,
  type,
  properties
) VALUES (
  $1, $2, $3, $4, $5
)
ON CONFLICT (flow_id, source_id, target_id, type) DO NOTHING
RETURNING id, flow_id, source_id, target_id, type, properties, created_at
`

type InsertWorldStateLinkParams struct {
	FlowID     int64           `json:"flow_id"`
	SourceID   int64           `json:"source_id"`
	TargetID   int64           `json:"target_id"`
	Type       string          `json:"type"`
	Properties json.RawMessage `json:"properties"`
}

func (q *Queries) InsertWorldStateLink(ctx context.Context, arg InsertWorldStateLinkParams) (WorldStateLink, error) {
	row := q.db.QueryRowContext(ctx, insertWorldStateLink,
		arg.FlowID,
		arg.SourceID,
		arg.TargetID,
		arg.Type,
		arg.Properties,
	)
	var i WorldStateLink
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.SourceID,
		&i.TargetID,
		&i.Type,
		&i.Properties,
		&i.CreatedAt,
	)
	return i, err
}

const lockWorldStateEntityByID = `-- name: LockWorldStateEntityByID :one
SELECT id, flow_id, entity_key, type, state, properties, annotations, version, created_at, updated_at
FROM world_state_entities
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockWorldStateEntityByID(ctx context.Context, id int64) (WorldStateEntity, error) {
	row := q.db.QueryRowContext(ctx, lockWorldStateEntityByID, id)
	var i WorldStateEntity
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.EntityKey,
		&i.Type,
		&i.State,
		&i.Properties,
		&i.Annotations,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockWorldStateEntityByKey = `-- name: LockWorldStateEntityByKey :one
SELECT id, flow_id, entity_key, type, state, properties, annotations, version, created_at, updated_at
FROM world_state_entities
WHERE flow_id = $1 AND entity_key = $2
FOR UPDATE
`

type LockWorldStateEntityByKeyParams struct {
	FlowID    int64  `json:"flow_id"`
	EntityKey string `json:"entity_key"`
}

func (q *Queries) LockWorldStateEntityByKey(ctx context.Context, arg LockWorldStateEntityByKeyParams) (WorldStateEntity, error) {
	row := q.db.QueryRowContext(ctx, lockWorldStateEntityByKey, arg.FlowID, arg.EntityKey)
	var i WorldStateEntity
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.EntityKey,
		&i.Type,
		&i.State,
		&i.Properties,
		&i.Annotations,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockWorldStateLink = `-- name: LockWorldStateLink :one
SELECT id, flow_id, source_id, target_id, type, properties, created_at
FROM world_state_links
WHERE flow_id = $1 AND source_id = $2 AND target_id = $3 AND type = $4
FOR UPDATE
`

type LockWorldStateLinkParams struct {
	FlowID   int64  `json:"flow_id"`
	SourceID int64  `json:"source_id"`
	TargetID int64  `json:"target_id"`
	Type     string `json:"type"`
}

func (q *Queries) LockWorldStateLink(ctx context.Context, arg LockWorldStateLinkParams) (WorldStateLink, error) {
	row := q.db.QueryRowContext(ctx, lockWorldStateLink,
		arg.FlowID,
		arg.SourceID,
		arg.TargetID,
		arg.Type,
	)
	var i WorldStateLink
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.SourceID,
		&i.TargetID,
		&i.Type,
		&i.Properties,
		&i.CreatedAt,
	)
	return i, err
}

const mergeWorldStateEntityProperties = `-- name: MergeWorldStateEntityProperties :one
UPDATE world_state_entities
SET
  properties = properties || $1::jsonb,
  updated_at = CURRENT_TIMESTAMP,
  version = version + 1
WHERE id = $2
RETURNING id, flow_id, entity_key, type, state, properties, annotations, version, created_at, updated_at
`

type MergeWorldStateEntityPropertiesParams struct {
	Properties json.RawMessage `json:"properties"`
	ID         int64           `json:"id"`
}

func (q *Queries) MergeWorldStateEntityProperties(ctx context.Context, arg MergeWorldStateEntityPropertiesParams) (WorldStateEntity, error) {
	row := q.db.QueryRowContext(ctx, mergeWorldStateEntityProperties, arg.Properties, arg.ID)
	var i WorldStateEntity
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.EntityKey,
		&i.Type,
		&i.State,
		&i.Properties,
		&i.Annotations,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const mergeWorldStateLinkProperties = `-- name: MergeWorldStateLinkProperties :one
UPDATE world_state_links
SET properties = properties || $1::jsonb
WHERE id = $2
RETURNING id, flow_id, source_id, target_id, type, properties, created_at
`

type MergeWorldStateLinkPropertiesParams struct {
	Properties json.RawMessage `json:"properties"`
	ID         int64           `json:"id"`
}

func (q *Queries) MergeWorldStateLinkProperties(ctx context.Context, arg MergeWorldStateLinkPropertiesParams) (WorldStateLink, error) {
	row := q.db.QueryRowContext(ctx, mergeWorldStateLinkProperties, arg.Properties, arg.ID)
	var i WorldStateLink
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.SourceID,
		&i.TargetID,
		&i.Type,
		&i.Properties,
		&i.CreatedAt,
	)
	return i, err
}

const updateWorldStateEntityState = `-- name: UpdateWorldStateEntityState :one
UPDATE world_state_entities
SET
  state = $1,
  updated_at = CURRENT_TIMESTAMP,
  version = version + 1
WHERE id = $2
RETURNING id, flow_id, entity_key, type, state, properties, annotations, version, created_at, updated_at
`

type UpdateWorldStateEntityStateParams struct {
	State WorldStateLifecycle `json:"state"`
	ID    int64               `json:"id"`
}

func (q *Queries) UpdateWorldStateEntityState(ctx context.Context, arg UpdateWorldStateEntityStateParams) (WorldStateEntity, error) {
	row := q.db.QueryRowContext(ctx, updateWorldStateEntityState, arg.State, arg.ID)
	var i WorldStateEntity
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.EntityKey,
		&i.Type,
		&i.State,
		&i.Properties,
		&i.Annotations,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
